apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gatus
  name: gatus-db
  annotations:
    numberOfReplicas: '1'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tns-csi-nvmeof
  resources:
    requests:
      storage: 250Mi