---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - grafana-instance.yaml
  - alloy-instance.yaml
  - servicemonitor.yaml
  - datasource-prometheus.yaml
  - dashboard-prometheus.yaml
  - secret.yaml