apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
stringData:
    client_secret: ENC[AES256_GCM,data:bHckIaYW+zfWBhDi4zu89uQ7FEG/LlK3wO/X+7cky10=,iv:uZGI5lkI3eTcD8GjJPuIcOk4jrooBQQWPZWnS1oGpoM=,tag:NqC1UKeOc/vMoMsVNlvuLA==,type:str]
    admin_user: ENC[AES256_GCM,data:bVTAk1st/jytxOM75Z8S5A==,iv:oRgjlFA5zmv6uVxai4qpbyeAVkVkTDZAOSINX5DuEmg=,tag:e5UVj+oTjC6GZRf6uo99nA==,type:str]
    admin_password: ENC[AES256_GCM,data:9XGtdFdWh0+5LhKL2nKRRkHBTAsTVc4aERo=,iv:E5v2b+rSH+aOrEURb8oM1LTbLvYplQi9ZxcJCP1md6c=,tag:UFYyxSYkPHTEzhmlhmkasg==,type:str]
    admin_email: ENC[AES256_GCM,data:i04OescM7uFf8/hqeRrvhQ==,iv:6y4gATUwFfI0wHrhEln0GdiX69d9FYBuY/SynWv7vtc=,tag:mRzUpUzdFnpm64wWCKqoWg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T12:32:57Z"
    mac: ENC[AES256_GCM,data:1HdJVXeCQ7IVkxC3dJHCtLJurncDbnCbw7HZBkFmgZ307DPnvAgfUWpuzHeFioFM4U74a/aMQukit6FVrL18b9AMGNBMk4TUDOTGciJKh8O8FRM76zIYpfbGmkdZo4XO6v1sBcqhRa186kdlNUiu2PFU/41w2nBCEzgSIZAmX1U=,iv:C2zowLbavKE/XlU4TsVQpJTSawZqgW4us2x0S+yS6t0=,tag:o7dx+c303qRW0J/SVxzAsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
