apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app.kubernetes.io/instance: longhorn
  name: longhorn-ingress
spec:
  tls:
    - hosts:
        - longhorn.local.traunseenet.com
      secretName: longhorn-cert
  ingressClassName: traefik
  rules:
    - host: longhorn.local.traunseenet.com
      http:
        paths:
          - backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
