apiVersion: v1
kind: Secret
metadata:
    name: s3-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QuTzghNzg6xdZIvbAeoTQKoPOl4=,iv:2tYpNy6IyvweNeauwPr8LC3lC7lYmOOtzD0T6WDo874=,tag:HxX56ySH3Utw/Q4v6krBTg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:MgW3mqYBtRc3sbnxmuxGCdd9aFd7ww==,iv:yKBAQStUTZQoBXesE7gyL/6qbu952Ko1WRITmdD6mwM=,tag:JQDLr1gandblA4EHIkxXEQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Do+OsKhrxct7uIxW2mCvFj/ofec4fzSTDqK9hGyiRAX8VVkplJ83Gw==,iv:jNaCDMhzi2dyTEwNrY1eVP5LwZfDkbzs7Zqx1tdGUD4=,tag:jG1U/fREhhTwfD79ky886A==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueHQ3Snc4VDJML0xuYkZJ
            NFdqVUh3Mkp4Y0xTeXJ4UCttc1Q1ZUdoQWtzCi9rR2t2YVUyM1JHSnVCQWt6bmY3
            TURZcjJobkJ6L2FYWWpNL0tCckp5OVUKLS0tIGp5V1JyNm1ubjFMQ1JKby9mNkk4
            Y0Jmd01kQzd5dEFOY2hDdmxac3JOczAKWUUKmONOVjHSIEwSxsJenpUPuOs0IlZY
            JHyppEtb1m1X1/u4/oO8oXjgdJJNpKCXjNuj7i3LI/HsbHsYMb/deA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T05:49:49Z"
    mac: ENC[AES256_GCM,data:+Ct/XP5eVglcPAXlOU4BxtnfyNNRdcw5ZdryKrC+AC1sN/bWBoA0Kz14jhEIqVyd9a3/wj0TX+BsAoRNWc60kGTG8zbhzOCBNdIaQx30cRL1eYrXI047LmbRYyVHJhNFLvI/ijevgHd4gzaPgFRRha1jQJNTBn8oXOXF7hEi+pw=,iv:/6CPU7qdsiVvS8xXJqyeK2ILiCSjt58BoOa/r38Hd5Y=,tag:Yw6eKpfl7b4C9yRt2/uVOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
