---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-backup
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataEngine: "v1"
  numberOfReplicas: "1"
  staleReplicaTimeout: "15"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  unmapMarkSnapChainRemoved: "ignored"
  migratable: "true"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataEngine: "v1"
  numberOfReplicas: "2"
  staleReplicaTimeout: "15"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  migratable: "true"
  unmapMarkSnapChainRemoved: "ignored"
---