apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secrets
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:c2U0KAutKC3YEBjzLnhNzOKlz3a2U3QrFtPL1Q/eIykSbhNWoDM=,iv:l02d459f9mGm4McDRMaF4WUJX702OqLv2cjgTGPAoAc=,tag:SfxuSdFC0LE7RTKgUAfXQQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:fKes0gNA6mDudy0nFd34q5jNgzNd01eADXa8cy7LadaaH4cs4H0=,iv:TP1Qm0y8dREeouq4gSUpqtCrMRWrtajplfHqXmYE4PI=,tag:5d35/Qi6YqmHTFXrI2WFmQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:du2WtLf1d5WU38f28yIVnbivi6aWo9bZ71HF0S7e+ri11S/IUJk=,iv:jmPvAQSvAwkH+I4V4lwRrdaCxQ2M9aFjnyU313yIdWY=,tag:hRK/KDtkg6QXldc935Ax8w==,type:str]
    KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:0PVQtd6RagDpA0vsFVrRsWOvn09WY0ZW211bc0lEIjkjctZB,iv:j0wkZI3yI2oPyR3s7KW8GDrMsUnVa2S9LOO0LK/wWMo=,tag:gxuZDBsh+S/LoBdlcAGK8Q==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:VhfiLgmJixjKKt2KdGKsyzh1JuoDbSwT/kyyR9V9eok=,iv:ECI7fAcP/l4eK2KTmrfhWQ2PnHwRMuVshlmewAvSsPs=,tag:e+CIBB4A8eBy4oyVYbXZJw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T08:16:30Z"
    mac: ENC[AES256_GCM,data:ixL+Pk3zUpj9soZJbtz7IMN+sWxy16U6YB2BnMk3UbCBkEUHFFTewQFRNiFtl3BGFhFuPhqZ/QeNbQAidmyuaKHouB2LZTvh1xSJaPHFF3Jb4G2L3Ey86PJZZsXfOgzyCLHDlo52CPr1n8Rsaba7idRO+1u6oxbuAnosnenVujU=,iv:PjDeBNrC92AYdjcTtws71B4QPFRLf/w3MLgtRL3VmVA=,tag:bp+/15KmoGBghhr36c30Hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
