---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: navidrome-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-addons
    - name: traefik-base
  path: ./kubernetes/apps/apps/navidrome/navidrome/app
  prune: true
  wait: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: navidrome
      namespace: apps
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: apps

