---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-beyla
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: beyla
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    tolerations: 
      - key: node-role.kubernetes.io/control-plane
        operator: "Exists"
        effect: "NoSchedule"
    serviceMonitor:
      enabled: true
    config:
      create: false
      name: "beyla-config"
      data:
        prometheus_export:
          port: 9090
          path: /metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
data:
  beyla-config.yml: |
    log_level: INFO
    routes:
      unmatched: heuristic
    discovery:
      services:
        - k8s_namespace: apps
        - k8s_namespace: default
        - k8s_namespace: networking
        - k8s_namespace: auth
        - k8s_namespace: secured
        - k8s_namespace: flux-system
        - exe_path: (worker)|(backend)|(frontend)|(cilium)|(hubble) # any service exec that has name worker,backent...
          namespace: kube-system
        # - k8s_namespace: storage
        # - exe_path: (worker)|(backend)|(frontend) # any service exec that has name worker,backent...
        #   namespace: MyApplication 
        #   name: "TestLoadGenerator" # overwrites the built in name with this
        # - exe_path: tcpforwarder 
        #   namespace: network
    trace_printer: text
    otel_traces_export:
      endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/traces
    otel_metrics_export:
      endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/metrics
    attributes:
      kubernetes:
        enable: true