---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
data:
  PAPERLESS_REDIS: redis://paperless-redis:6379
  PAPERLESS_DBHOST: paperless-pg-rw
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_DBNAME: paperless
  PAPERLESS_PORT: "8000"
  PAPERLESS_URL: https://paperless.cloud.traunseenet.com
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
  PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
  PAPERLESS_OCR_LANGUAGES: "deu+eng"
  TZ: "Europe/Vienna"
  PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
  PAPERLESS_DISABLE_REGULAR_LOGIN: "true"