apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- configmap.yaml
- ingress.yaml
- pg.yaml
- service.yaml
- deployment.yaml
- redis.yaml
- pvc.yaml
- gotenberg.yaml
- tika.yaml
