apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:b+rn4flLQ2yYsP/W6lr8bqtlMeiP6n96OW6WcXgWiqVLbVUjYMowhB2YtgxgRMOiWLMy4HdSq0pKWQoPRuuj1Q==,iv:gaNYDEfUm4DmZv9UjXLA7LxA8vRaC+D46OmvRClbBUs=,tag:lIiFa6rMRWx1+GMWODUpbA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:lb+uxjVzwvDDrw==,iv:BkR/m0srXx1NEAv/zMZ//1vMR7XG+GgJXVVgIBTcLgs=,tag:mV2xXkJMqRgRBwrg7a73YA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BQ23uwTOHPXhY1OE/ARIACTtDGnCt3vE7/kOYFMsrPZyNW/V+CuGLJ3lTKBXrjYpGEHw/UjNk59F5Pw3SSM29w==,iv:ZXE0DIZcY2oKkpTwAJGXx/zuj4p/Ln3gkj3kpup4r4U=,tag:kge4qH/sj0gS1X9YNhgDeQ==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:DZsc60BKSnjO+6yrXQ8Boj4=,iv:S7khTNE2NIcxeeQrUr+WgjTfVJYL/xURr6nN82QIpsw=,tag:CDAQnZshGnbpDl+FqwCtPA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T13:42:20Z"
    mac: ENC[AES256_GCM,data:SOVlb0SFC7Ez7JN0PPPy/cAytBuNu1daZ3EugK8Tci4T9RxgS6USg1xsCBkNrjLXcZUSuNLyjjnay2cbcXSms7dN5UWL1itUA3Cc15hNoriNxTHZhLkVtOY+avNeqWL9EmGhyJNPPDv8aNtFRyFyqP0stkQY5h5ZFrM9jTlbdsY=,iv:hQmiS3czYu862Mh1xYdP883Elkby3sJCyEzjJa0HjM0=,tag:J+wulzbFCsjrZ9BnynA8sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-paperless
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Q7Tu0S5Fx56Myvq4gn0RSoXy5OxQ9NGMo3J2wtopxYV7aQ8hatZcHK3JdGBUbCShL4LsPPp4Q0IR,iv:gBh6soskiYbMPNPhg8VbLTe0ukndwAOSc95YDHozDqs=,tag:bTBV7P4mYo53wB1quHreEA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:h5PpwG0Hqe8z/FbteSA1EhMzg8KGKlGDHExczcxM4n9ifJFspQwF2+s2,iv:QRFMz0aIl1l1iU5IGyHLQhXK/eNgwqc9JKc1+q+dF+8=,tag:vvDIsQe6wqRNWg3fh6+wvA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zQYchXDD06D1OLDaaJK60BIsr5o=,iv:WRFfRJqKcFPHcMR0LV9WS2AcvYS7k1y5NxGydZwK9eg=,tag:mkm/p1kt+QjyNr6xLR+JRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1ydCU/k5eFsJFpQBLldan1tKHZEaZtnVg6K+O86QHpGk7gFZ/I61nw==,iv:IkDuVMcynCXLLV4nnpuXXmeGKhnNy0iOfndldiTgtVw=,tag:67k18ABLGcxqTyxKDdjjHw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T13:42:20Z"
    mac: ENC[AES256_GCM,data:SOVlb0SFC7Ez7JN0PPPy/cAytBuNu1daZ3EugK8Tci4T9RxgS6USg1xsCBkNrjLXcZUSuNLyjjnay2cbcXSms7dN5UWL1itUA3Cc15hNoriNxTHZhLkVtOY+avNeqWL9EmGhyJNPPDv8aNtFRyFyqP0stkQY5h5ZFrM9jTlbdsY=,iv:hQmiS3czYu862Mh1xYdP883Elkby3sJCyEzjJa0HjM0=,tag:J+wulzbFCsjrZ9BnynA8sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-paperless-pg-backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zQYchXDD06D1OLDaaJK60BIsr5o=,iv:WRFfRJqKcFPHcMR0LV9WS2AcvYS7k1y5NxGydZwK9eg=,tag:mkm/p1kt+QjyNr6xLR+JRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1ydCU/k5eFsJFpQBLldan1tKHZEaZtnVg6K+O86QHpGk7gFZ/I61nw==,iv:IkDuVMcynCXLLV4nnpuXXmeGKhnNy0iOfndldiTgtVw=,tag:67k18ABLGcxqTyxKDdjjHw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T13:42:20Z"
    mac: ENC[AES256_GCM,data:SOVlb0SFC7Ez7JN0PPPy/cAytBuNu1daZ3EugK8Tci4T9RxgS6USg1xsCBkNrjLXcZUSuNLyjjnay2cbcXSms7dN5UWL1itUA3Cc15hNoriNxTHZhLkVtOY+avNeqWL9EmGhyJNPPDv8aNtFRyFyqP0stkQY5h5ZFrM9jTlbdsY=,iv:hQmiS3czYu862Mh1xYdP883Elkby3sJCyEzjJa0HjM0=,tag:J+wulzbFCsjrZ9BnynA8sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
