---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./cert-manager.yaml
  - ./longhorn.yaml
  - ./traefik.yaml
  - ./backube.yaml
  - ./open-webui.yaml
  - ./priaeus.yaml
  - ./harbor.yaml
  - ./renovate.yaml
  - ./opentelemetry.yaml
  - ./jaeger.yaml
  - ./grafana.yaml