apiVersion: v1
kind: Secret
metadata:
    name: github-token-secret
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:et9h0uLapaPiACjzQGRUCnkwTdIrUw3o+55KY2Ui254YFIpfyyrY+A==,iv:NekMfD7xM5Zni0GVDgcO45/aGUeGA5BuAsoJPEyrcjc=,tag:kLZq0dOuTpiuiGbEPr0PPQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaDNCd2twbXpFaWNzSk51
            Y0RxYnZGQ2FESjV1NEpwR0lTQTRuaTVpcjNZCkdLam1OK1duWHBIZmRxUzlnRWxQ
            UmttSzR5M1JLMEY0SFhmVXlzcEJyak0KLS0tIC9jZ1ZOZUl0MlBBNEdCWitlNmtK
            R2lna1VKSmJqbGRrUE1MR0pNVS80MGMKLveSSZFwBvmPZJaIhPKI6IrQY3TMcAY4
            l7ASwlfKcP2gUxqEAyYI9iE8C2x5z7+ND5k9mvPRFYfPxsvcuNwIBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T21:25:16Z"
    mac: ENC[AES256_GCM,data:lzkPpREjCBx1ndMKGtdc3ZFlomfiu0LK+5PQEup21n/0mwxCDo2dlNeeyEB7ixaIyuIxHGjVOgGKHobk5ZbLUrM4ZOW+HQaqkXzJK3i92nThs8/nv8/WviP3GA0jLo9tHMShYoLloIY5b2eFYD9DP4CEeox7aRfYLUnJOg1lGeQ=,iv:+ZRH3+l0b6X41SVVxJaiGQlGjMyuuvp8BZndfelDWks=,tag:WaC/zeHBUl29Uj8wkbfOTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
