---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-app
  namespace: flux-system
spec:
  dependsOn:
    - name: tns-csi
  path: ./kubernetes/apps/observability/prometheus/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: prometheus-stack
      namespace: observability
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: observability
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-rules
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-app
  path: ./kubernetes/apps/observability/prometheus/rules
  prune: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 15m
  timeout: 5m
  targetNamespace: observability