apiVersion: v1
kind: Secret
metadata:
    name: netbird-secrets
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:HmjEOt2rEkATMsYbENDA/ISL/jBeTRKzAUT0lZvWv2aUOZCI85ej1w==,iv:T78+69r0kIxxEWycR8xxdGm/CbQJ9s9QZCuKHdD2bV8=,tag:zARAjI8t6EZ02mWMHryc5Q==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T09:28:10Z"
    mac: ENC[AES256_GCM,data:4vM995088REmaopy6kbcRnjTfmaDV+UH5ivoz08obb+mP1NGxbHlIeL7iHNfRqipBAOQE/gu7Btkt5NU69ENy/g0vZWKmfPkVjbIwFUAvbbw7E8omTwZZ5GA+v3tVVEmcuoZ4V3PZT8zFMEtv8O4BpFyOJYa6ffhaPTFjB8R1YU=,iv:rkEPAnxenSEcO6La8KipkqUX9CYLKu1t1TXljkn+L3E=,tag:neqPgbMLbWytcQnWhnWzuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
