---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pangolin-proxy
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/pangolin-proxy/pangolin-proxy/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: networking
  dependsOn:
    - name: prometheus-app
