apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-id
  labels:
    app: pocketid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
    spec:
      containers:
        - name: pocket-id
          image: ghcr.io/pocket-id/pocket-id:v2.3.0
          env:
            - name: APP_URL
              value: "https://pocketid.cloud.traunseenet.com"
            - name: TRUST_PROXY
              value: "true"
          ports:
            - containerPort: 1411
              name: http
              protocol: TCP
          volumeMounts:
            - name: pocketid-data
              mountPath: /app/data
          livenessProbe:
            exec:
              command:
                - /app/pocket-id
                - healthcheck
            initialDelaySeconds: 10
            periodSeconds: 90
            timeoutSeconds: 5
            failureThreshold: 2
          readinessProbe:
            exec:
              command:
                - /app/pocket-id
                - healthcheck
            initialDelaySeconds: 10
            periodSeconds: 90
            timeoutSeconds: 5
            failureThreshold: 2
      volumes:
        - name: pocketid-data
          persistentVolumeClaim:
            claimName: pocketid-data

