apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocket-id
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: pocketid
spec:
  tls:
    - hosts:
        - pocketid.cloud.traunseenet.com
      secretName: pocketid-cert
  ingressClassName: traefik
  rules:
    - host: pocketid.cloud.traunseenet.com
      http:
        paths:
          - backend:
              service:
                name: pocket-id
                port:
                  number: 1411
            path: /
            pathType: Prefix

