apiVersion: v1
kind: Secret
metadata:
    name: restic-pocketid
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:5yQqij+I55ddjENnxjMFDkW6tkx4TBpyMnpctjat+AAPmsqee8bCHLHHYhAOkbnVW4+LrXFq9O8=,iv:5YD1WHbv5TWD4+nVxQabZfUttLq8zarOC0kMr/eG6NA=,tag:0ihIckuYLCQni3o24FJHRg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:9FxdyErcV3/qYxGEhSPNegpYwkxw89kuVyg03Yzaqy04iOxKFQ==,iv:Z4EY3nGVR3oaZCMJRnhQM0Bk4QhBgfFVGdTQM1XhZvI=,tag:Q1rOI/iJYiw/5AvQ6fHgRQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fBKBliE17VQCiMdNw0uOpTobpGU=,iv:Kq0D+kADDYYOtCeaEHaPfDtrfi0uLDPSMJY3VJQHdYY=,tag:BN3PMYsCVY+pE6KY0MB42A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Qf/WnxxNerkA5HGP0XjbL1agj6V2f5On/boJhfe2vqs1Vs6jGwWZmg==,iv:4BTWum9FQ3Usw8AtAv9eQa2R+FD+799PfD2gm7huSDw=,tag:L7oSuj3CLwAt6+xiuA4uJw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T08:27:04Z"
    mac: ENC[AES256_GCM,data:eKTgReBDb+xdA+LWDUPqCBzCb6X21Jfa+DgBEahAoqozmqr/Hb/Kw8tOrCQXW76URlgMZiFEw6SrVmcI/+3A5/ZTge7iTJyX6/WntBptbh0zjCoKIG+nUeG12kKhChCOjHlhceu8+i9uWJWRRPJEAkFcc5fy2f+DGESCQagVAwI=,iv:FuOH3s7qUmsbI/00smW3aIaZFDorYz+ICM0amBmsO/Y=,tag:MZRh7Si2JAyamT7S56txLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
