apiVersion: v1
kind: Service
metadata:
  name: pocket-id
  labels:
    app: pocketid
spec:
  type: ClusterIP
  selector:
    app: pocketid
  ports:
    - name: http
      protocol: TCP
      port: 1411
      targetPort: 1411

