---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tns-csi
  namespace: storage
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bfenski/tns-csi-driver
  ref:
    tag: 0.9.2
