---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: reactive-resume-postgres
  name: reactive-resume-postgres-data
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-storage
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: reactive-resume-postgres-restore
  resources:
    requests:
      storage: 2Gi
status: {}
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: reactive-resume-postgres-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-reactive-resume-postgres
    storageClassName: longhorn-storage
    accessModes: ["ReadWriteMany"]
    copyMethod: Snapshot
    capacity: 2Gi
    enableFileDeletion: false
    cleanupCachePVC: false
    cleanupTempPVC: false
