apiVersion: v1
kind: Secret
metadata:
    name: reactive-resume-secrets
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:TkAtY2ALOf9hZOthJbAdcy826pRMvGc=,iv:BER7AnbrherJu0N39WaPVlB5cj4xZOzM6dqGD4z2ZbE=,tag:xXU0+9dDXh60pVDvflM/MA==,type:str]
    postgres-url: ENC[AES256_GCM,data:Svlyk8S8EtMqNMKbAXRQfq8huJoyYZtTI2Jw2ofr3LkcorF8t/gPup9Kw6kgWgxNx+2IRbxUWpuJBbPwrrrHcAjyrfE=,iv:INgbbX5i4hv7mxUyUcOlJORSFrgn6K2WZ21x92VSV4o=,tag:P2gOiKzRsOtdrnfvmhdDBA==,type:str]
    chrome-token: ENC[AES256_GCM,data:UZTSdrOmTmeFrK8S2lxft0Z7zmQ=,iv:crmBQQkflx1F2248BAfP6ZdufXXzGeTWY8DaVTlQmDo=,tag:fDAf3VOGA5G+3yFY8s5DpA==,type:str]
    access-token-secret: ENC[AES256_GCM,data:mGIer/FcNW0YMbmWy8jV0W4HLSlljmZ7IY2Dz50QGZg=,iv:PZjX8x4g56yFsOl65GmMwmJrU0pOdqD52RAaEEIdFog=,tag:CWFRn2LJHWM40AEbWblreQ==,type:str]
    refresh-token-secret: ENC[AES256_GCM,data:j/ToqqXJnW4VtuuM77h+OyabAHE8jTRPDsSfAshX+J8=,iv:oZhoFRva7Qc/sxxHIfeGlm7QIqy/GXCgwKXMb7bYjFk=,tag:4ZyEDjUWY45IgMP5jmKlWQ==,type:str]
    storage-access-key: ENC[AES256_GCM,data:KbiCw/GHTZAcWmtKCaFqtSKD+VM=,iv:U11ql9PfTxmrlNtIa9Y3Ea784f8wwBWMtVjK33nlxGY=,tag:cU69/DEjv4aZ51lYIDDlqQ==,type:str]
    storage-secret-key: ENC[AES256_GCM,data:ULI7U5IYo8kOaZLnIw2F8qNsCUjngOfCQ5f61DRiP30httV5Pjwu8g==,iv:InU6dyRVI3pnBeg4MOKue4g9iABbRgj0BSoDhOaphFg=,tag:qeRm4k1jHwtEYVIATFH1+Q==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZGloMFNUZjNZbTk2UGZk
            T1RQcnY2WFVlWE1yQVlwN1dwV2VqREJwcEZjCnhLaGpQdFE0RVBwYzMwaVVUbjZM
            c29rb2ZHSmdQMmk4RVMxNnQzajA5OVkKLS0tIGR1aXAyUzhzd2FiZlJQeEwrOXBB
            Vk96bmpvdmpRS0N4ekNwSXhMajA2TDQKxRWZ3EIaWpuTa/Q8OhrMTjrzxr/bilj4
            0emlpEbVguDMSnGUxpw0VYgZhY6p1zLYO2oPjuoktjfaFnen4ATRaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T13:48:57Z"
    mac: ENC[AES256_GCM,data:3OPFy+FjVJ5OhRdSZ57wCqy/zmYQYPxEPKFMSyr6Da94eXngODEhs8MzlyAw+SleSdjECmFsyR8w5BbddkHGm8tMR0G1c2E+n/lMeU5HLUcjrcXYZ3f/Vuje14Cv9Y7SyUJCsVUNGvsUAFOADi0Jx8Lg235NKOVjevFhCFDxtdU=,iv:li47XfcV/0DRcITQTMofo47P17qUE+nCcAuY4PVZIzs=,tag:0whJa+SfAcwLv8JJ4xKUJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-reactive-resume-postgres
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:M4zjk/pR9VhvuE/A1lPKI63QJZBXZeJfITwZt54zL8OFSJzmbYQsiXvX09xb3v9qzvVXPRCYZbN6MTtP3LlgSehWL+pjHsos,iv:fn7V9N0k+MHN81fHUarG5mP5OZoZAGwH6aIqfXFovXM=,tag:cmE5ImxblNOnXcyAq+XHmQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ZyCIuJIr6eUk/gfoJlv/pJR0gPIMPTccnnMmcpZujTGyvEUcsMUQJmli/l4Gqs57Ew==,iv:pGcvGg2FMHx97BZW8UV7rFbvH6Gy6pMiAKy9E0hTYP4=,tag:JG+783lFTooUNgHrpujlZw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:COfO4BX3w7GlIrTMHW8itZzbAo8=,iv:7HTJKMr0ZdxW0u0SakpFUhn1w7uVJHw/wu/pyZRVoSU=,tag:E5q3L60Luqpjx4P6dU5MDA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4SDSm4VdyA4+8RkvXOh0d6Vx8V/oR9iuVQnyxaFjyrNl9Ljv4UoMBw==,iv:5Cs9xx5Ilm4oWAOzndB99S3JHZIo8qA2dMnOj83s4LM=,tag:xEmGoe8TaVQlNw1yF5jsVQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZGloMFNUZjNZbTk2UGZk
            T1RQcnY2WFVlWE1yQVlwN1dwV2VqREJwcEZjCnhLaGpQdFE0RVBwYzMwaVVUbjZM
            c29rb2ZHSmdQMmk4RVMxNnQzajA5OVkKLS0tIGR1aXAyUzhzd2FiZlJQeEwrOXBB
            Vk96bmpvdmpRS0N4ekNwSXhMajA2TDQKxRWZ3EIaWpuTa/Q8OhrMTjrzxr/bilj4
            0emlpEbVguDMSnGUxpw0VYgZhY6p1zLYO2oPjuoktjfaFnen4ATRaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T13:48:57Z"
    mac: ENC[AES256_GCM,data:3OPFy+FjVJ5OhRdSZ57wCqy/zmYQYPxEPKFMSyr6Da94eXngODEhs8MzlyAw+SleSdjECmFsyR8w5BbddkHGm8tMR0G1c2E+n/lMeU5HLUcjrcXYZ3f/Vuje14Cv9Y7SyUJCsVUNGvsUAFOADi0Jx8Lg235NKOVjevFhCFDxtdU=,iv:li47XfcV/0DRcITQTMofo47P17qUE+nCcAuY4PVZIzs=,tag:0whJa+SfAcwLv8JJ4xKUJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
