---
apiVersion: v1
kind: Service
metadata:
  name: cerebro-db
  labels:
    app.kubernetes.io/name: cerebro-db
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cerebro-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP