---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cerebro
  name: cerebro-config
  annotations:
    numberOfReplicas: '1'
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: tns-csi-nvmeof-retain
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: cerebro-restore
  resources:
    requests:
      storage: 1Gi