apiVersion: v1
kind: Secret
metadata:
    name: cerebro-secrets
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:UwinBEHZvWkoh0dK4fITeojYA0ywMqlldAnQfniSQFlTfIojxrgDy+/OQ+lSKBs3rqz3AJsTcMzvqvVl3N6J5AZMla0UvW4ZipDJ0SGrtA/9,iv:8xnob/BqyLFJDkcvyOtqXvvUCAwnxTfSn303Ctc//2Q=,tag:7QdhrnGBTzSEJFT9gPaDrQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Gs1pFxFUK6s=,iv:gg2UZsddVhSmmsn9tZt4NKgBPGsl42QVh7rL/aqS+pA=,tag:CQ7CH1gRAMtYVxH+1A2mMg==,type:str]
    SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:HHHhZILxKOgtayEibsfgz98GbeJloVC+xML4RHhBfCp/5eCoxJMwsJvP,iv:aD7vn2YUlOybFK7THtab4EGud+4NuTMYGpSqDOc1ziY=,tag:+kdy5eVdJAtro+dGwIFJWg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WQt/vZhxVWHkpIcTFQQutSJa30+6MnOqAg==,iv:oemeifaesX58nLjcgB9k2lPhR/268FKrqc5AgfrTAuA=,tag:LvFJF0JUid6asRGmnGkYUw==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:F3HG0MkpUSK9Yktdt7Hv55WLwCagX3hruGSUJqexKqsy0gPQ,iv:zURXI9/YFqGjel2EeuqNCh4sOiWOQsN1Z8W0+k23PCI=,tag:sJjDT1m9nadqLkMYeB472g==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:dEtE5NvPYhSCYrzamg9PoU/WzLXSp2phIT1mpxmlKRk=,iv:1ewOqMtYtulPZV5sk4zHoH94hejq5DaUNMXVlPk8MXM=,tag:GKxjfQCdhbPCPmCjmRPswg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T20:03:41Z"
    mac: ENC[AES256_GCM,data:ZOuT4dTMw/w+s73mj9/1mMc302vvEaGtSKAklBqGPUYcWNocPI4i0EOZSGcNPbI5gyhT3qttrcFtdFNChaEswvx0gTmN5kU8g2lwAsojN2x+3c0FSZmJRW7hhQv4eF8sAngs8w0tM1B4IgOIiHAqAFwCDq3NajZcO6aQP5Nxezw=,iv:U7rZwE7G4jTUWz/GR4h8+y8jQjH1pVT3Z+FxwDQM2E4=,tag:XBv7E2lR2C/VpYwxqS9Usg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
