apiVersion: v1
kind: Secret
metadata:
    name: cerebro-secrets
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:UwinBEHZvWkoh0dK4fITeojYA0ywMqlldAnQfniSQFlTfIojxrgDy+/OQ+lSKBs3rqz3AJsTcMzvqvVl3N6J5AZMla0UvW4ZipDJ0SGrtA/9,iv:8xnob/BqyLFJDkcvyOtqXvvUCAwnxTfSn303Ctc//2Q=,tag:7QdhrnGBTzSEJFT9gPaDrQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Gs1pFxFUK6s=,iv:gg2UZsddVhSmmsn9tZt4NKgBPGsl42QVh7rL/aqS+pA=,tag:CQ7CH1gRAMtYVxH+1A2mMg==,type:str]
    SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:HHHhZILxKOgtayEibsfgz98GbeJloVC+xML4RHhBfCp/5eCoxJMwsJvP,iv:aD7vn2YUlOybFK7THtab4EGud+4NuTMYGpSqDOc1ziY=,tag:+kdy5eVdJAtro+dGwIFJWg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WQt/vZhxVWHkpIcTFQQutSJa30+6MnOqAg==,iv:oemeifaesX58nLjcgB9k2lPhR/268FKrqc5AgfrTAuA=,tag:LvFJF0JUid6asRGmnGkYUw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T19:35:55Z"
    mac: ENC[AES256_GCM,data:3hAoOE7p6DSN5Xvvi9giQ4yUjeurhaIeRUux8rFaa8N5QaZW0VotfVJImHwESMACPcAzMKxcb7YjM+8rwYi67Ov8m+tnKgP7g0ZqTjZYrcRsfBdTOvTllnDtz5nxgivjD+WCPHG1GW671PPAH4YfHHR/pHLIvQwRx54EA1bUYAY=,iv:AYZhJxoa1ku5cVjSGyScUk+mDlvJaC8ZgYnivH4/nSo=,tag:V/DXOhrCQgMesbUgFk+Uuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
