apiVersion: v1
kind: Secret
metadata:
    name: cerebro-secrets
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:UwinBEHZvWkoh0dK4fITeojYA0ywMqlldAnQfniSQFlTfIojxrgDy+/OQ+lSKBs3rqz3AJsTcMzvqvVl3N6J5AZMla0UvW4ZipDJ0SGrtA/9,iv:8xnob/BqyLFJDkcvyOtqXvvUCAwnxTfSn303Ctc//2Q=,tag:7QdhrnGBTzSEJFT9gPaDrQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Gs1pFxFUK6s=,iv:gg2UZsddVhSmmsn9tZt4NKgBPGsl42QVh7rL/aqS+pA=,tag:CQ7CH1gRAMtYVxH+1A2mMg==,type:str]
    SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:HHHhZILxKOgtayEibsfgz98GbeJloVC+xML4RHhBfCp/5eCoxJMwsJvP,iv:aD7vn2YUlOybFK7THtab4EGud+4NuTMYGpSqDOc1ziY=,tag:+kdy5eVdJAtro+dGwIFJWg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WQt/vZhxVWHkpIcTFQQutSJa30+6MnOqAg==,iv:oemeifaesX58nLjcgB9k2lPhR/268FKrqc5AgfrTAuA=,tag:LvFJF0JUid6asRGmnGkYUw==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:F3HG0MkpUSK9Yktdt7Hv55WLwCagX3hruGSUJqexKqsy0gPQ,iv:zURXI9/YFqGjel2EeuqNCh4sOiWOQsN1Z8W0+k23PCI=,tag:sJjDT1m9nadqLkMYeB472g==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:dEtE5NvPYhSCYrzamg9PoU/WzLXSp2phIT1mpxmlKRk=,iv:1ewOqMtYtulPZV5sk4zHoH94hejq5DaUNMXVlPk8MXM=,tag:GKxjfQCdhbPCPmCjmRPswg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T06:33:35Z"
    mac: ENC[AES256_GCM,data:Xw93H1dIK/uBajflfP1/qSpkjPpK+7XTrjAR5YJAq+zpFAyP1Rf518i1+yjTclQSxB4hGgaZUmtyMn+7LuhD58F0c7g81FpVsvmFRLngO4poffu+7PIywdJ0vIi6vz9MbTgVPzquP5i6UOjsZh6Fm7wNHv5e5AieQ1EhKrvwOyc=,iv:3mqr6VKuc8T8SsE+aLuUU4KDUTeimiJRPOIg0hcLYMY=,tag:pXC9gq6nqc0E1hbtFOizBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-cerebro
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:yswjlfzxGWkHSryIR3jdivlTI0RQ+qNT2YqRkvuAlP3kfH7aKFsXPFQOxDov17cWyVA0UnoucQ==,iv:0C7E1qKSF5p4hMgi1eLzoPz0kN8vw0K/1NjNpFKVwJQ=,tag:RIyJf+/WmASD7mh/42XPqQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:+09aBmDcaFxU3/MrvtoNWbK8Sx/6mFtVT+9JKWeYfU1QMbIWCPRunT2BgAKarC0=,iv:SFYHLi1PpIT3MvtxFWtw3ot8Z/hCTc5SqYX972Ql9Fk=,tag:AXlF3MyNW//JrJlknjsWrw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zQYchXDD06D1OLDaaJK60BIsr5o=,iv:WRFfRJqKcFPHcMR0LV9WS2AcvYS7k1y5NxGydZwK9eg=,tag:mkm/p1kt+QjyNr6xLR+JRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1ydCU/k5eFsJFpQBLldan1tKHZEaZtnVg6K+O86QHpGk7gFZ/I61nw==,iv:IkDuVMcynCXLLV4nnpuXXmeGKhnNy0iOfndldiTgtVw=,tag:67k18ABLGcxqTyxKDdjjHw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T06:33:35Z"
    mac: ENC[AES256_GCM,data:Xw93H1dIK/uBajflfP1/qSpkjPpK+7XTrjAR5YJAq+zpFAyP1Rf518i1+yjTclQSxB4hGgaZUmtyMn+7LuhD58F0c7g81FpVsvmFRLngO4poffu+7PIywdJ0vIi6vz9MbTgVPzquP5i6UOjsZh6Fm7wNHv5e5AieQ1EhKrvwOyc=,iv:3mqr6VKuc8T8SsE+aLuUU4KDUTeimiJRPOIg0hcLYMY=,tag:pXC9gq6nqc0E1hbtFOizBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
