---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-addons
    - name: traefik-base
    - name: harbor-app
  path: ./kubernetes/apps/apps/it-tools/it-tools/app
  prune: true
  wait: true
  suspend: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Deployment
      name: it-tools
      namespace: apps
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: apps