---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbird-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/netbird/netbird/operator
  dependsOn:
    - name: cert-manager-addons
  prune: true
  suspend: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 15m
  timeout: 5m
  targetNamespace: networking