---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui-app
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-base
  path: ./kubernetes/apps/apps/open-webui/open-webui/app
  prune: true
  wait: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: apps
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui-backup
  namespace: flux-system
spec:
  dependsOn:
    - name: open-webui-app
  path: ./kubernetes/apps/apps/open-webui/open-webui/backup
  prune: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: apps