---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  dependsOn:
    - name: tns-csi
  path: ./kubernetes/apps/storage/cnpg/cnpg/app
  prune: true
  wait: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: barman-cloud
    namespace: storage
  - apiVersion: apps/v1
    kind: Deployment
    name: cloudnative-pg-operator
    namespace: storage
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: storage