apiVersion: v1
kind: Secret
metadata:
    name: restic-harbor
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:62NHbYOTrgqyL0rkNE5uT0in/ACCrOB3XHFcEtaDlrVF4nFtZ2UpzGXqZWbtYBxOkLzWbSnC,iv:gKq0Ugz1maebNOJcY7B/CldelzhJjmSDwNB5wnyf6kk=,tag:jZ3dLHLey0JOYZiR+XqgEA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:9FxdyErcV3/qYxGEhSPNegpYwkxw89kuVyg03Yzaqy04iOxKFQ==,iv:Z4EY3nGVR3oaZCMJRnhQM0Bk4QhBgfFVGdTQM1XhZvI=,tag:Q1rOI/iJYiw/5AvQ6fHgRQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fBKBliE17VQCiMdNw0uOpTobpGU=,iv:Kq0D+kADDYYOtCeaEHaPfDtrfi0uLDPSMJY3VJQHdYY=,tag:BN3PMYsCVY+pE6KY0MB42A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Qf/WnxxNerkA5HGP0XjbL1agj6V2f5On/boJhfe2vqs1Vs6jGwWZmg==,iv:4BTWum9FQ3Usw8AtAv9eQa2R+FD+799PfD2gm7huSDw=,tag:L7oSuj3CLwAt6+xiuA4uJw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T13:43:50Z"
    mac: ENC[AES256_GCM,data:hcgzUTeVgHTtBmohGQVE9CA4pWeF1Sm6fNrOQGIVZwMFswkEiUyCGbv0OFAInviNrOiKdsaOnRlxtAnRKuxr88pf5pjOZQWC2kB8MMTddINuHtg8enhJqIeO/rRf1wRYA8jVhY0XEUaaae1hFmK2kd7JyBLcpvB2e8FpObSpwKE=,iv:+AjcWVHsrs6tgZjU4PPIFtPSeHcvmHD710yn3QSroGg=,tag:ue8LDIsV9yXcVElnVugQSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: harbor-secret
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:+lHJuCQZf/LYk1Fw/blaZko/a3rONVg=,iv:NpKK0+zrgfgY5uag20a/mP/2tc6oqRaXHQ8x5TDA0hs=,tag:HZ8ZeEbkfKZu69egDegSaQ==,type:str]
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:Lyl3yRamZArtrXTsVGMk7VC91Ys=,iv:1E3BYoNliwV/9wELQVqAWVU+iEe9Y88XIR2k7fsWvn0=,tag:WTJFH/7GU5MrJgdj+TfhyQ==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:Ht2Zvm4Gi5U+KKEPrqVoPaIh6LPeTqBtxYF80n9VloKFnWZmUABzQw==,iv:L+Jk/DpnBfW3CrXEIMdffSy9ylXM03Z3Gc4DzKt9OtE=,tag:Q5Qd3QVaPqR9Oqpi+I2zGQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T13:43:50Z"
    mac: ENC[AES256_GCM,data:hcgzUTeVgHTtBmohGQVE9CA4pWeF1Sm6fNrOQGIVZwMFswkEiUyCGbv0OFAInviNrOiKdsaOnRlxtAnRKuxr88pf5pjOZQWC2kB8MMTddINuHtg8enhJqIeO/rRf1wRYA8jVhY0XEUaaae1hFmK2kd7JyBLcpvB2e8FpObSpwKE=,iv:+AjcWVHsrs6tgZjU4PPIFtPSeHcvmHD710yn3QSroGg=,tag:ue8LDIsV9yXcVElnVugQSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
