apiVersion: v1
kind: Secret
metadata:
    name: restic-harbor
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:62NHbYOTrgqyL0rkNE5uT0in/ACCrOB3XHFcEtaDlrVF4nFtZ2UpzGXqZWbtYBxOkLzWbSnC,iv:gKq0Ugz1maebNOJcY7B/CldelzhJjmSDwNB5wnyf6kk=,tag:jZ3dLHLey0JOYZiR+XqgEA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:9FxdyErcV3/qYxGEhSPNegpYwkxw89kuVyg03Yzaqy04iOxKFQ==,iv:Z4EY3nGVR3oaZCMJRnhQM0Bk4QhBgfFVGdTQM1XhZvI=,tag:Q1rOI/iJYiw/5AvQ6fHgRQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fBKBliE17VQCiMdNw0uOpTobpGU=,iv:Kq0D+kADDYYOtCeaEHaPfDtrfi0uLDPSMJY3VJQHdYY=,tag:BN3PMYsCVY+pE6KY0MB42A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Qf/WnxxNerkA5HGP0XjbL1agj6V2f5On/boJhfe2vqs1Vs6jGwWZmg==,iv:4BTWum9FQ3Usw8AtAv9eQa2R+FD+799PfD2gm7huSDw=,tag:L7oSuj3CLwAt6+xiuA4uJw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T16:44:15Z"
    mac: ENC[AES256_GCM,data:ym+IYmglDk+ROGhgHBqZaWHhWo5CtoZntl3QkLYCSQFINn32wn7NkLAlU2ESNsa8fzZFQSPs6q6V0gC8IzmdS6aPidmHC+XpNxN4lZHy8mROFJcYSM0wFNb2/vm9kQmUPrxF3frACW7Zfz4H4wpUO+gDYeZWzQ9jjNghE9+LObA=,iv:E2kDDO8owBdbwJgwaqYr6XMpSSoNR5FitQpNaJQPAfg=,tag:wFdcnY/BUPN96sHb9NoSrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: harbor-secret
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:+lHJuCQZf/LYk1Fw/blaZko/a3rONVg=,iv:NpKK0+zrgfgY5uag20a/mP/2tc6oqRaXHQ8x5TDA0hs=,tag:HZ8ZeEbkfKZu69egDegSaQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T16:44:15Z"
    mac: ENC[AES256_GCM,data:ym+IYmglDk+ROGhgHBqZaWHhWo5CtoZntl3QkLYCSQFINn32wn7NkLAlU2ESNsa8fzZFQSPs6q6V0gC8IzmdS6aPidmHC+XpNxN4lZHy8mROFJcYSM0wFNb2/vm9kQmUPrxF3frACW7Zfz4H4wpUO+gDYeZWzQ9jjNghE9+LObA=,iv:E2kDDO8owBdbwJgwaqYr6XMpSSoNR5FitQpNaJQPAfg=,tag:wFdcnY/BUPN96sHb9NoSrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
