apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  labels:
    app: newt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt
  template:
    metadata:
      labels:
        app: newt
    spec:
      containers:
        - name: newt
          image: fosrl/newt
          env:
            - name: PANGOLIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: newt-secret
                  key: PANGOLIN_ENDPOINT
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: newt-secret
                  key: NEWT_ID
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: newt-secret
                  key: NEWT_SECRET
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          imagePullPolicy: IfNotPresent
