apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: homelab-newt-egress-policy
spec:
  podSelector:
    matchLabels:
      app: homelab-newt
  policyTypes:
    - Egress
  egress:
    # Allow access to internal NPM
    - to:
        - ipBlock:
            cidr: 10.0.0.103/32
      ports:
        - protocol: TCP
          port: 443
    # Allow access to internal DNS
    - to:
        - ipBlock:
            cidr: 10.0.0.102/32
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    # Allow access to internal docker vm
    - to:
        - ipBlock:
            cidr: 10.0.0.151/32
    # Allow access to pangolin https & udp ports
    - to:
        - ipBlock:
            cidr: 116.203.125.9/32
      ports:
        - protocol: TCP
          port: 443
        - protocol: UDP
          port: 51820
        - protocol: UDP
          port: 21820
    # Allow kube-dns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53