# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - homeNetworkPolicy.yaml
  - k8sNetworkPolicy.yaml
  - devopsNetworkPolicy.yaml
  - secret.yaml
