apiVersion: v1
kind: Secret
metadata:
    name: newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:o26/xEZruLU8jKhN0W/jMKOu8VQvH1MPHQn20b4z5no=,iv:pX+TOoYHEiRwSXvWeFG53FEWaqRNAwHj6KA9PAe5rhA=,tag:M6T4CFEAKKGJqtJi64qqNw==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:apbPXhsXoO/OwK5o8Bdb,iv:koGfQ2SSJfmPxBJ39CvvbA+NR6WpEa9qOPgomMVN8yw=,tag:pJBWJy/3xlkQI4kGNRlJJw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:bcnK0QXjW1oNtrv/arVTRsyxMc7ynVjXPkOk6Mc/wJEcSeAAQB8lARO21bnEW+sP,iv:KehwTiyx0kbL6HB3bmcoyrdTxKcR2L+Ke5i+eYJYa2E=,tag:bpC1aGnudb9A8qxGQhnnwA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T21:13:58Z"
    mac: ENC[AES256_GCM,data:Dd6JQkDH0dnVk63kBFGG+92MGXroB2Xr2oZngPL7NjsgcPn/8VIeS/4hbay+VbEU/5uJ8yGp1iBeOTbj2o4+ieqJfvTxmqiHCznTykjZAfK1ds0F2DrSLSH+suF1CD08TGoa8PmTQEKBnUY4RzbefEacSU7pEzHeQEtACSQYD0g=,iv:TFX0aiL57cLeg42KR/zSUx3pLOpW/lOFBgR89qj84q0=,tag:DE96b7ZGSOoLNHe/1n6m8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
