apiVersion: v1
kind: Secret
metadata:
    name: k8s-newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:o26/xEZruLU8jKhN0W/jMKOu8VQvH1MPHQn20b4z5no=,iv:pX+TOoYHEiRwSXvWeFG53FEWaqRNAwHj6KA9PAe5rhA=,tag:M6T4CFEAKKGJqtJi64qqNw==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:pKIQTdheO55JTwYUmQfl,iv:fNKMESbAI7n7/XnAHHlSdK5s8grKI86f564sr6bv7HI=,tag:Wl6ngk28gfgwXFG938zn4g==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:nuiOiV2pTtsM18R34IY7qvy6K/yPGNX2b3bAQKD0m72WTV/aY4gB7orv8j7t5FSi,iv:NdfNRmuOYhj/Gr6BrBegTt1tSST4EohGF+BXzXKymNE=,tag:t+8J/9TzNlJ4EfkCt6hqzQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:29:56Z"
    mac: ENC[AES256_GCM,data:aqfU7Ir8jACFLWtckByDECycvtb21X5ZQD/+7Eq2UE6M9hgvtD58t/fsk9HxaBfV01o6cb+RU/VGfzFIaUlzPIgQiAMix+3lFbOf+mpJpUtvh1WMJJOPT2MqwogJNsKuEWdHtklokJFEfN1OlknMP77XTXLoRAtosAAFIaGlHVc=,iv:Vg1dHnfGIJSKt6JmTXyKUekglFQz5qQTYPd74OUgWk0=,tag:I+A41O+gCeC2b++yPdCESg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: homelab-newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:o26/xEZruLU8jKhN0W/jMKOu8VQvH1MPHQn20b4z5no=,iv:pX+TOoYHEiRwSXvWeFG53FEWaqRNAwHj6KA9PAe5rhA=,tag:M6T4CFEAKKGJqtJi64qqNw==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:KU7uHfLc4KoNOv/+0eiN,iv:WOc+YTLsaP4hOKkkPMwSbbWYWTDlg8cPqkWDLUg7+Q4=,tag:JIufrTbQehtBF5zVcJ7p1g==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:gB0HUJDfZ8ADbL7Y2di2PeFS/6HAD/e3o/dLuYGfDviZuVIyIspsrjL8DnEWkt9O,iv:WFRD9aOz98ZSSIq8rc1faXQBJoffZdx7Cz78KbKx37U=,tag:nyd1GkVx173EYndusgeY/w==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:29:56Z"
    mac: ENC[AES256_GCM,data:aqfU7Ir8jACFLWtckByDECycvtb21X5ZQD/+7Eq2UE6M9hgvtD58t/fsk9HxaBfV01o6cb+RU/VGfzFIaUlzPIgQiAMix+3lFbOf+mpJpUtvh1WMJJOPT2MqwogJNsKuEWdHtklokJFEfN1OlknMP77XTXLoRAtosAAFIaGlHVc=,iv:Vg1dHnfGIJSKt6JmTXyKUekglFQz5qQTYPd74OUgWk0=,tag:I+A41O+gCeC2b++yPdCESg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: devops-access-newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:o26/xEZruLU8jKhN0W/jMKOu8VQvH1MPHQn20b4z5no=,iv:pX+TOoYHEiRwSXvWeFG53FEWaqRNAwHj6KA9PAe5rhA=,tag:M6T4CFEAKKGJqtJi64qqNw==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:PGnKD1XczGS0TI8HS88b,iv:AVorRMI+muRA8DmU1bauwpkfXl6YK6xYiJKaex9KbhE=,tag:Jg+Dq9AXrRLLUu9vTC8w3A==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:2U37wGHaEZceKZJ/5506xP1YS9oNciFkoIpHQTg3vM8XA7r9FuywkK8zsKBF4RBy,iv:LW51rgz69cWsR0ZlO+Aao81B5iDkOB+8IVmRyIbLq3Y=,tag:/7F2ep0wDVfCx2ZQLJZbvg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:29:56Z"
    mac: ENC[AES256_GCM,data:aqfU7Ir8jACFLWtckByDECycvtb21X5ZQD/+7Eq2UE6M9hgvtD58t/fsk9HxaBfV01o6cb+RU/VGfzFIaUlzPIgQiAMix+3lFbOf+mpJpUtvh1WMJJOPT2MqwogJNsKuEWdHtklokJFEfN1OlknMP77XTXLoRAtosAAFIaGlHVc=,iv:Vg1dHnfGIJSKt6JmTXyKUekglFQz5qQTYPd74OUgWk0=,tag:I+A41O+gCeC2b++yPdCESg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
