apiVersion: v1
kind: Secret
metadata:
    name: newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:o26/xEZruLU8jKhN0W/jMKOu8VQvH1MPHQn20b4z5no=,iv:pX+TOoYHEiRwSXvWeFG53FEWaqRNAwHj6KA9PAe5rhA=,tag:M6T4CFEAKKGJqtJi64qqNw==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:pKIQTdheO55JTwYUmQfl,iv:fNKMESbAI7n7/XnAHHlSdK5s8grKI86f564sr6bv7HI=,tag:Wl6ngk28gfgwXFG938zn4g==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:nuiOiV2pTtsM18R34IY7qvy6K/yPGNX2b3bAQKD0m72WTV/aY4gB7orv8j7t5FSi,iv:NdfNRmuOYhj/Gr6BrBegTt1tSST4EohGF+BXzXKymNE=,tag:t+8J/9TzNlJ4EfkCt6hqzQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T06:39:36Z"
    mac: ENC[AES256_GCM,data:caBlKg0X5dc0ogPJaGYggs4/HGzOcoHjWPjiULak8lrdxzVWG3HqCtBZqqt9P56oKc9cS12T14XO1ERMdGK7rNGBpmAlapY3xqtW/AQSKJ943XoAB6gRnvg/atAb1n0X9oqLRQEojn1A1CWoGuQBx7EbQfwNcnPmBve6mtUcvhQ=,iv:7rGC+ZccbCTDdwZxvzcIAbDG9Ey9aowyPYwBw6MRuPY=,tag:8ymAhOa2NkudNDA4IKlrvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
