apiVersion: v1
kind: Secret
metadata:
    name: restic-linkwarden
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:lkTI6nIDmY6efg3BKfutEyS35SLD/fr3m+IlpiaSESFdcl5OVpwFAd9Hkm1mvlA4fNWqM4CcbnCFLQ==,iv:eggPsqqz3LKiUtTg3bKbSpG1Hzu8LypY1a7PhreiirM=,tag:tQjiasD3JDCaTRfkiWi3Tg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:z3B+KidBNrvcr2RceYjc/SlsVWrZwNbbWikpKDD484xkef97tg==,iv:1pvjGMUhqg6HeVOEZSkNOzPPDlba2FQurbjn8rBUKhU=,tag:sE3iZ0vA7955UP4OMz/VfQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:orY+nxbCff2j7u3tGvvRaxAWWWo=,iv:gFnTQh4TV247tYPNM/31qTWX42kh6X2BMmNClkoNEr0=,tag:j94WwCRWw3l5Z3dVvQX6uA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SckICNv/xQ/lJ7nt07x6/cRl5/MnroctUlCMyvJlWj/svRUWNBegAw==,iv:wnBmpG6cAV3XZCOqJwH/lKHDUj2MiXu/VPlZq4NntbY=,tag:G5hp9uIcuDFMrgFRyjzI0w==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUEZQanlxUmNBSm9meHJI
            cUkrUFo2bjNic05Eajc1elR0WU55K2NCZTNZCm1hRGM3TkNWN1ZHYXo5TGMvaGJa
            T3JFaUhCdEdNUmJqNGdWTWYvRk5WWHcKLS0tIGcxNFZZVmlNQXFHZ2NrZHFVWnow
            eHVuY0RlRTF5MXZkTDJuUjF6Tjh2L28KZVBMgcEAyZSkdtCMXvbZDVAbAK1GYZ+G
            V1heMti6zhmfqjyFR5hz8yG1e+9200v1JeyyNBJ+TggSM/gOlCZsYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T08:04:09Z"
    mac: ENC[AES256_GCM,data:GUl4ieaBNYO9DMDPRpTrKnIcXd1t2oz+DipBiZoFe7mt6lEgP2kwvy9VeHrjA9qKLp1kWwAlc4fKdoYqRfmYwKTUPjfNuSGYj6qWZiPPLlgEuBsEaUiCmWowuQKRQ8QZ/IrWNOo5c18XVGffr4Ccs5wZu0h2M0RqeiBTVEm4wmI=,iv:BMvAH5SA8oNvE9gXudEYNH4l9lHT+EAWtl4IehyKCh8=,tag:D3q82cYgKS9EsQ+KPRdfaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
