---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./prometheus/ks.yaml
  - ./grafana/ks.yaml
  - ./jaeger/ks.yaml
  - ./otelcol/ks.yaml
  - namespace.yaml