---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karakeep
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: karakeep
spec:
  tls:
    - hosts:
        - karakeep.cloud.traunseenet.com
      secretName: karakeep-cert
  ingressClassName: traefik
  rules:
    - host: karakeep.cloud.traunseenet.com
      http:
        paths:
          - backend:
              service:
                name: karakeep
                port:
                  number: 80
            path: /
            pathType: Prefix
