apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:c2U0KAutKC3YEBjzLnhNzOKlz3a2U3QrFtPL1Q/eIykSbhNWoDM=,iv:l02d459f9mGm4McDRMaF4WUJX702OqLv2cjgTGPAoAc=,tag:SfxuSdFC0LE7RTKgUAfXQQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:fKes0gNA6mDudy0nFd34q5jNgzNd01eADXa8cy7LadaaH4cs4H0=,iv:TP1Qm0y8dREeouq4gSUpqtCrMRWrtajplfHqXmYE4PI=,tag:5d35/Qi6YqmHTFXrI2WFmQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:du2WtLf1d5WU38f28yIVnbivi6aWo9bZ71HF0S7e+ri11S/IUJk=,iv:jmPvAQSvAwkH+I4V4lwRrdaCxQ2M9aFjnyU313yIdWY=,tag:hRK/KDtkg6QXldc935Ax8w==,type:str]
    OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:1tjGPXaSDoOK8SqXaQzcd6V3+eDF8YSLH8RP78SpaDO1MNobYbk2BtTfjy+dsgfOB/9hSoknIbu75XWzGsw8xbNfByYgxrQ=,iv:Ag/ixNUrVYEswygcygfEYUBGJHt88Z5eFlqEE+E1MVM=,tag:rSnns4SUMrrND2dMa/9vsQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:J32fVci8Ks963RHCygMq0RC1gy+R1HSzAu7JbDxKu7E=,iv:Ppq1GrKSrhTjYn/FU0xDX5JxhuWlwacKmdextGclYH0=,tag:uHaZDDxRyqcbXlmghYVLqw==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:95nOT6ffkZTHGCkppI0YEFcrKxPHoTI/4TcQHP7BCTs7OUfL,iv:JvY/qHkFkGQzZw6D4MaTqXmBLpyc27QkWkvRLBLVEBg=,tag:PMHU/F6YmJLTMuZWVFrImQ==,type:str]
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:41/L4ZepeO2V,iv:YOoD1Y3l9A72j1NQ4UTQKrvNl5dTGaDymuft/oHATwg=,tag:0aKxBOYFpfPsi+/GbCRkvg==,type:str]
    DISABLE_PASSWORD_AUTH: ENC[AES256_GCM,data:MguVQQ==,iv:iNRYECL31QJ4+ey9Q0tR7cXvrlyQQnNbQONzN5ARzJU=,tag:/j4x7UcianOuyxmxrkrfZA==,type:str]
    OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: ENC[AES256_GCM,data:csOObw==,iv:HHg4jePEeXH+Z4iw4YFKjvtbZiIjA2km8QJPpHiyjYA=,tag:gZ7Jij42oiZyegLJw8hA6Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:blXD,iv:eiwlBMiLuRVlbgLecZAwMBeFrKbNx4T+qXR+o4s+azs=,tag:SlAq7RhBH/Cz1VLPdJ8dGQ==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:NlEZALimcBnzq9+qr6kM6xNssHxGQpSkGg==,iv:kcd5R+VjEloYjYa8/UgBAoEcHuWb5KzJfUGe/qBFQyI=,tag:V7NHhuTUd2xfKyxHOunRJw==,type:str]
    INFERENCE_TEXT_MODEL: ENC[AES256_GCM,data:9ZYaQYhiNtP4HsLsxQ==,iv:nIYHKHkH+0NZ/O5KDWznOpvCi78fdzkKQvehrAPjqys=,tag:nUlBdgQ7m8pUthPUgcNu6g==,type:str]
    EMBEDDING_TEXT_MODEL: ENC[AES256_GCM,data:oJqhwOmHPtmRVHySoWjC9H6GDA==,iv:51dMHuxbzD6Di9c1mxK72W7NQ39Ads4uxe7ZRWRRVJ4=,tag:/oaeuO6/w/jq/EIqqJH1iQ==,type:str]
    INFERENCE_CONTEXT_LENGTH: ENC[AES256_GCM,data:thKsnYs=,iv:Y2PNZ+3F7MpxDmHFvQ6KDEc2+Q8773gPWx/yYywP0z4=,tag:W2hjUHD0UBHPSqki+HL31A==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T07:14:16Z"
    mac: ENC[AES256_GCM,data:A+0XSgbxfZd7BTgR3mm+A+XHu9PplQwF0apd91J3aeYx2Ck7UMqhqb0Zd5w6J1UN5JHqDtybgYONcqg2kg2SRWl3N94nmlrvec8P1+QSPGV7D747stcPnYpsqDcOuKdGh8VubNCrYCPx/d8moYZ6go0TBeSBqbTDMkkdfWp3Gyk=,iv:XohSsGeH8k8DWgGjaoI1i7h7rELJFe4JMU88Z7KfM2Y=,tag:Okd37W412T/mG+Z/Jg4pLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-karakeep
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:RW1zkT9b7qFyweUrvX5HzlPWn6S7FU9HIzLzWs2YvKkxtGzSAGICPSPCvrcrr+47X1EQnMstoVY=,iv:xcVzTuOBw1Pjhvg3pdQrkYb93FCZCVPrKeFCLO5pDrw=,tag:ql31QVPZFEAdK/A7RwCY4A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Zu+w50AerhDSWalQK7giDQmFEdXstrY5B6VschtsuPnMGwHR8w==,iv:7wdMago3vxI7f7/eiOyCbDQh9Yf4R2usgRU7/yQARjk=,tag:3pc7wJGmzevyyK3vP1RMhA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6fMZOZyN67r1Ml+af8xe2uEmWMQ=,iv:vAp5DYPQK7JW62NSMgruw9ek6y1kSyPIoCCkNfQIvVM=,tag:zO+H14lQQy51E9lUl0F1ZA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Fnsq6TnSEk9/zR+vrCE5qUribf2IVGjzv4wUk4xkOjhr6/5ZxZeK8w==,iv:cD4i2UgKWEdi0ijM0qbiuUOybmTMpsH82ggngEOjk+o=,tag:eIg4m8WZRcLquYLAqJygLw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T07:14:16Z"
    mac: ENC[AES256_GCM,data:A+0XSgbxfZd7BTgR3mm+A+XHu9PplQwF0apd91J3aeYx2Ck7UMqhqb0Zd5w6J1UN5JHqDtybgYONcqg2kg2SRWl3N94nmlrvec8P1+QSPGV7D747stcPnYpsqDcOuKdGh8VubNCrYCPx/d8moYZ6go0TBeSBqbTDMkkdfWp3Gyk=,iv:XohSsGeH8k8DWgGjaoI1i7h7rELJFe4JMU88Z7KfM2Y=,tag:Okd37W412T/mG+Z/Jg4pLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
