apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:c2U0KAutKC3YEBjzLnhNzOKlz3a2U3QrFtPL1Q/eIykSbhNWoDM=,iv:l02d459f9mGm4McDRMaF4WUJX702OqLv2cjgTGPAoAc=,tag:SfxuSdFC0LE7RTKgUAfXQQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:fKes0gNA6mDudy0nFd34q5jNgzNd01eADXa8cy7LadaaH4cs4H0=,iv:TP1Qm0y8dREeouq4gSUpqtCrMRWrtajplfHqXmYE4PI=,tag:5d35/Qi6YqmHTFXrI2WFmQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:du2WtLf1d5WU38f28yIVnbivi6aWo9bZ71HF0S7e+ri11S/IUJk=,iv:jmPvAQSvAwkH+I4V4lwRrdaCxQ2M9aFjnyU313yIdWY=,tag:hRK/KDtkg6QXldc935Ax8w==,type:str]
    OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:54jDTR6Dd6f+OIGXLVqolAREuZLoTn/zlAaQG9t52xkdJe3cigqq9SSzRqAKSdfFlchYjO6Nlr+w/L2RPWp+gGM=,iv:+wWygtuwIlcxCzQGj3nlOkADXepw6V1e3otR40/VJ9U=,tag:CXB04lqfgejLFqRUYTbm+g==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:kVXyXixtwihXqjHRhglBz8rO/xkEDolA0nGsSbYaPUQ=,iv:hlDB3vLxhzqwzg5UaJP/zSTZdQM58VMJnBWdYb3OSnk=,tag:b1wxNBCnID/sDtdY2wa7Ww==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:zjGo222Y6uVdiI4vk+zSLdhGVLZfUh8qDiLlQf5M5BBt0L7a,iv:D4nnhpu1YHj+Pa0HM0BUXVW1nT3N41EGqbAyi8O0KXQ=,tag:P00/AqT5mH2Z5pTN4BkWiA==,type:str]
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:41/L4ZepeO2V,iv:YOoD1Y3l9A72j1NQ4UTQKrvNl5dTGaDymuft/oHATwg=,tag:0aKxBOYFpfPsi+/GbCRkvg==,type:str]
    DISABLE_PASSWORD_AUTH: ENC[AES256_GCM,data:MguVQQ==,iv:iNRYECL31QJ4+ey9Q0tR7cXvrlyQQnNbQONzN5ARzJU=,tag:/j4x7UcianOuyxmxrkrfZA==,type:str]
    OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: ENC[AES256_GCM,data:csOObw==,iv:HHg4jePEeXH+Z4iw4YFKjvtbZiIjA2km8QJPpHiyjYA=,tag:gZ7Jij42oiZyegLJw8hA6Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:blXD,iv:eiwlBMiLuRVlbgLecZAwMBeFrKbNx4T+qXR+o4s+azs=,tag:SlAq7RhBH/Cz1VLPdJ8dGQ==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:NlEZALimcBnzq9+qr6kM6xNssHxGQpSkGg==,iv:kcd5R+VjEloYjYa8/UgBAoEcHuWb5KzJfUGe/qBFQyI=,tag:V7NHhuTUd2xfKyxHOunRJw==,type:str]
    INFERENCE_TEXT_MODEL: ENC[AES256_GCM,data:9ZYaQYhiNtP4HsLsxQ==,iv:nIYHKHkH+0NZ/O5KDWznOpvCi78fdzkKQvehrAPjqys=,tag:nUlBdgQ7m8pUthPUgcNu6g==,type:str]
    EMBEDDING_TEXT_MODEL: ENC[AES256_GCM,data:oJqhwOmHPtmRVHySoWjC9H6GDA==,iv:51dMHuxbzD6Di9c1mxK72W7NQ39Ads4uxe7ZRWRRVJ4=,tag:/oaeuO6/w/jq/EIqqJH1iQ==,type:str]
    INFERENCE_CONTEXT_LENGTH: ENC[AES256_GCM,data:thKsnYs=,iv:Y2PNZ+3F7MpxDmHFvQ6KDEc2+Q8773gPWx/yYywP0z4=,tag:W2hjUHD0UBHPSqki+HL31A==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T16:06:32Z"
    mac: ENC[AES256_GCM,data:dhpwPfOGKrem5dvHn60wfVSdiLw9zJMj7R2XQWkcN4VF19GcS310/t0+G5jguQaFHLonqzPqpayKnfqBtNLLmIamkP9Z+0sJ98ysZ6hpFlNY/2Eur6O4TAe1SCJzQBeLkfsT1TMeHWCrsiEnEc0JRjv5FUdg9bQdVb6QWqs+JxA=,iv:IZhvbgC6/2xanQ6gql/PNhhcRyHPqSQYmqveSY5ireA=,tag:0MXZ6QunYUbJFYm9zOltPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-karakeep
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:TaYbExnw1SHySVQvvRPxDljyBBJ5Ik/ogMgD9Dl+r5+uRUU9B3tlLMFUmmS3q/NBKpy7eNealBQ=,iv:dA1aQFxLQ4n+NFwzBOXo+peH1YlytzO83Sfoa+3kQVA=,tag:bfys/cxaXbtOP3TmRbGQSA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:CJ6Zqaecq+/+/PO5zxNVEP+gkIXHtS5rkujp15eS1iOukJsKeziK5J8=,iv:Tz21VK1AndEY4W1PUQq8QZMJK/ePV70QV4G/4PHL4tc=,tag:3S591ki93iDTnFDjzVNNSg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ynJ4NCayvzNe1YDI//qSE+ILRT0=,iv:l6PmVbgjs/OoPv3Znsw0GVGxxXhDNNsfLRchcW7FJsE=,tag:q4nKkK0vhdbX0hCfaM1wRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KbxeUqgXB+VdGAfZQ8KwwkMQNkcWk6h6U0iz2rtjuZi2Pxnr9bT2EA==,iv:OrcmvPcHb71PNnd00dOljn9rOzvKaqJ9baV4h66JWU0=,tag:x5vzc6IXvYocS/B4iTkdTA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T16:06:32Z"
    mac: ENC[AES256_GCM,data:dhpwPfOGKrem5dvHn60wfVSdiLw9zJMj7R2XQWkcN4VF19GcS310/t0+G5jguQaFHLonqzPqpayKnfqBtNLLmIamkP9Z+0sJ98ysZ6hpFlNY/2Eur6O4TAe1SCJzQBeLkfsT1TMeHWCrsiEnEc0JRjv5FUdg9bQdVb6QWqs+JxA=,iv:IZhvbgC6/2xanQ6gql/PNhhcRyHPqSQYmqveSY5ireA=,tag:0MXZ6QunYUbJFYm9zOltPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
