---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otel-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-addons
  path: ./kubernetes/apps/observability/otelcol/otelcol/operator
  prune: true
  wait: true
  suspend: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: observability
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otel-collector
  namespace: flux-system
spec:
  dependsOn:
    - name: otel-operator
  path: ./kubernetes/apps/observability/otelcol/otelcol/operator/collector
  prune: true
  wait: true
  suspend: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: observability