---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cerebro-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - cerebro.cloud.traunseenet.com
      secretName: cerebro-cert
  ingressClassName: traefik
  rules:
    - host: cerebro.cloud.traunseenet.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cerebro-server
                port:
                  name: http-tcp
