---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocketid-base
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-addons
    - name: longhorn-addons
    - name: traefik-addons
  path: ./kubernetes/apps/auth/pocketid/pocketid/base
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: pocketid-data
      namespace: auth
  interval: 15m
  retryInterval: 15m
  timeout: 5m
  targetNamespace: auth
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocketid-addons
  namespace: flux-system
spec:
  dependsOn:
    - name: pocketid-base
  path: ./kubernetes/apps/auth/pocketid/pocketid/addons
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 5m
  targetNamespace: auth

