---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocketid-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-addons
    - name: traefik-base
    - name: longhorn-addons
    - name: harbor-app
  path: ./kubernetes/apps/auth/pocketid/pocketid/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Deployment
      name: pocket-id
      namespace: auth
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: auth
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocketid-backup
  namespace: flux-system
spec:
  dependsOn:
    - name: pocketid-app
  path: ./kubernetes/apps/auth/pocketid/pocketid/backup
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: auth