---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio
  name: minio-data
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-storage
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: minio-restore  # Name of the ReplicationDestination
  resources:
    requests:
      storage: 5Gi
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: minio-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-minio
    storageClassName: longhorn-storage
    accessModes: ["ReadWriteOnce"]
    copyMethod: Snapshot
    capacity: 5Gi
    enableFileDeletion: false
    cleanupCachePVC: false
    cleanupTempPVC: false
