apiVersion: v1
kind: Secret
metadata:
    name: restic-minio
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bcPyGzrrhmSQxifBEFSJcv752aAFF45ESjZq1FUgmUyXo7s1Llwo8lSh4AIHaC2TTyBVf6k=,iv:CP70gRBLgkvTo0H0sNKmrsiA0JwCCMM8PxxZiLprjh4=,tag:9j1VSq4uiKsy+mL1pWJWog==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:+MIcrmHMtZbH8kN5Ban0R4mp9zHtZzYrRV0DpPmYJvSnEQwG65EI6TVqHbxrnTjRrg==,iv:BSfbez4n10QIv/x1FvbV0qrk2N1kD3+REM7+GnnO++o=,tag:0qie/UeQiHZ6gGqnNoCFqw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JzEwcloBfiPaTKWd09Vhl0IoC7g=,iv:I1QMWyZVWpHQGTannTLGs5N63P7tS7eTelihCBA8Dhk=,tag:uJqYmoXcySE2i48W7BKgXg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BX4ChSVLoqqQFNknuBlQyDbjvQyqZvERvTyWRC5NAFYFOPniSaShIQ==,iv:4G2Gep3UaVaSnsgWWyBO2/A3a3T40snmJqFckfWxriE=,tag:qh7oeu7krY7WLni2jWN+dQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL0hFUDc2RzEzeHhMdjVh
            N1dDaE9XVCtiN3BST29mMG94N2pFV21mRVU4CnZpeDY4TStQekRGMnVoN1hHZC9k
            Qm9lUTNPVDV3bW82NnRXMmdSY1dmWUUKLS0tIHN6ODRGa1R0Q0wrQWlUMzllZDND
            cWVlT0dmdDR4ajF5WnVjUnFlYTM1TG8KpziHmRszNsDzAfueJm/Jrk9qk2Oy+Q5G
            raPUl8uZCkGB9TwWtLv5s7AIk9eTadj3gVVI60shKOOiFar6L1/aoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T07:03:26Z"
    mac: ENC[AES256_GCM,data:J9MpKOzprLQypG/95y/G+wjO9bot2deVSSMG9bHviS9mHuhi6mz7sYiD4VBn6UbZbukhiiVr5aqBncDKsImumJe+WbPNtrTmeh/7xC+1mfkAxh7GcnRM41XCdvvFDL1Hano78RikckOXA37RNJXJ6Oqn4CXVtxbyTEgYmRo4vlo=,iv:nkIdnfPmvDNq8CElARG89hjaKMSGYy541Ptz7Y/L+kw=,tag:G5pR1FXemUWiRLMAhxjTzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
stringData:
    username: ENC[AES256_GCM,data:L6RoUpu05LG0hw==,iv:BZE1Zxtd4evIGVYSbKTMMBJj+QeWei2pDpuxSLCZM00=,tag:KxUYYtJcl0YwfYq6becp5w==,type:str]
    password: ENC[AES256_GCM,data:7An3DsXdgkyJx2QCPE/9ZSMAdBnee0E=,iv:PO7sZbMVLZQBAijiDPVhOq/7dPe3omjyFtobyccfizU=,tag:l13uTLj9m/hImeseXYDbcg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL0hFUDc2RzEzeHhMdjVh
            N1dDaE9XVCtiN3BST29mMG94N2pFV21mRVU4CnZpeDY4TStQekRGMnVoN1hHZC9k
            Qm9lUTNPVDV3bW82NnRXMmdSY1dmWUUKLS0tIHN6ODRGa1R0Q0wrQWlUMzllZDND
            cWVlT0dmdDR4ajF5WnVjUnFlYTM1TG8KpziHmRszNsDzAfueJm/Jrk9qk2Oy+Q5G
            raPUl8uZCkGB9TwWtLv5s7AIk9eTadj3gVVI60shKOOiFar6L1/aoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T07:03:26Z"
    mac: ENC[AES256_GCM,data:J9MpKOzprLQypG/95y/G+wjO9bot2deVSSMG9bHviS9mHuhi6mz7sYiD4VBn6UbZbukhiiVr5aqBncDKsImumJe+WbPNtrTmeh/7xC+1mfkAxh7GcnRM41XCdvvFDL1Hano78RikckOXA37RNJXJ6Oqn4CXVtxbyTEgYmRo4vlo=,iv:nkIdnfPmvDNq8CElARG89hjaKMSGYy541Ptz7Y/L+kw=,tag:G5pR1FXemUWiRLMAhxjTzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
