apiVersion: v1
kind: Secret
metadata:
    name: restic-minio
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bcPyGzrrhmSQxifBEFSJcv752aAFF45ESjZq1FUgmUyXo7s1Llwo8lSh4AIHaC2TTyBVf6k=,iv:CP70gRBLgkvTo0H0sNKmrsiA0JwCCMM8PxxZiLprjh4=,tag:9j1VSq4uiKsy+mL1pWJWog==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:+MIcrmHMtZbH8kN5Ban0R4mp9zHtZzYrRV0DpPmYJvSnEQwG65EI6TVqHbxrnTjRrg==,iv:BSfbez4n10QIv/x1FvbV0qrk2N1kD3+REM7+GnnO++o=,tag:0qie/UeQiHZ6gGqnNoCFqw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JzEwcloBfiPaTKWd09Vhl0IoC7g=,iv:I1QMWyZVWpHQGTannTLGs5N63P7tS7eTelihCBA8Dhk=,tag:uJqYmoXcySE2i48W7BKgXg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BX4ChSVLoqqQFNknuBlQyDbjvQyqZvERvTyWRC5NAFYFOPniSaShIQ==,iv:4G2Gep3UaVaSnsgWWyBO2/A3a3T40snmJqFckfWxriE=,tag:qh7oeu7krY7WLni2jWN+dQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL0hFUDc2RzEzeHhMdjVh
            N1dDaE9XVCtiN3BST29mMG94N2pFV21mRVU4CnZpeDY4TStQekRGMnVoN1hHZC9k
            Qm9lUTNPVDV3bW82NnRXMmdSY1dmWUUKLS0tIHN6ODRGa1R0Q0wrQWlUMzllZDND
            cWVlT0dmdDR4ajF5WnVjUnFlYTM1TG8KpziHmRszNsDzAfueJm/Jrk9qk2Oy+Q5G
            raPUl8uZCkGB9TwWtLv5s7AIk9eTadj3gVVI60shKOOiFar6L1/aoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T06:19:10Z"
    mac: ENC[AES256_GCM,data:LrdngWb53GStJlMRWm9klKfDqNJxZa/9X0Qnp8by5Q4l2DEdzxXW2DUY9/k4St4wy3QLDmCAK8w8DOINk4xLaXfzFyhHDa9JifAygIzl8Mmm3i+XFts8g/PPZ3jMRWQ5Vyh8A5M2hZwT++qy9/Jr3aiG/INYAiWdvuBM6U/PMVI=,iv:BMJ4Zr34A3KLySCOs3uPIjpru/QjUR5IVztG7m6i5os=,tag:lzLbFYUUnQuzPN2pdD/aNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
stringData:
    username: ENC[AES256_GCM,data:JoKssKAI/K9zxQ==,iv:NAddKlzQ21kpMymd6PKQ3kxiqEK3VyfiGt6aAoUv0Ng=,tag:zQlhua4RXZ6l45YT4RdqmQ==,type:str]
    password: ENC[AES256_GCM,data:7An3DsXdgkyJx2QCPE/9ZSMAdBnee0E=,iv:PO7sZbMVLZQBAijiDPVhOq/7dPe3omjyFtobyccfizU=,tag:l13uTLj9m/hImeseXYDbcg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL0hFUDc2RzEzeHhMdjVh
            N1dDaE9XVCtiN3BST29mMG94N2pFV21mRVU4CnZpeDY4TStQekRGMnVoN1hHZC9k
            Qm9lUTNPVDV3bW82NnRXMmdSY1dmWUUKLS0tIHN6ODRGa1R0Q0wrQWlUMzllZDND
            cWVlT0dmdDR4ajF5WnVjUnFlYTM1TG8KpziHmRszNsDzAfueJm/Jrk9qk2Oy+Q5G
            raPUl8uZCkGB9TwWtLv5s7AIk9eTadj3gVVI60shKOOiFar6L1/aoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T06:19:10Z"
    mac: ENC[AES256_GCM,data:LrdngWb53GStJlMRWm9klKfDqNJxZa/9X0Qnp8by5Q4l2DEdzxXW2DUY9/k4St4wy3QLDmCAK8w8DOINk4xLaXfzFyhHDa9JifAygIzl8Mmm3i+XFts8g/PPZ3jMRWQ5Vyh8A5M2hZwT++qy9/Jr3aiG/INYAiWdvuBM6U/PMVI=,iv:BMJ4Zr34A3KLySCOs3uPIjpru/QjUR5IVztG7m6i5os=,tag:lzLbFYUUnQuzPN2pdD/aNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
