apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
stringData:
    username: ENC[AES256_GCM,data:L6RoUpu05LG0hw==,iv:BZE1Zxtd4evIGVYSbKTMMBJj+QeWei2pDpuxSLCZM00=,tag:KxUYYtJcl0YwfYq6becp5w==,type:str]
    password: ENC[AES256_GCM,data:7An3DsXdgkyJx2QCPE/9ZSMAdBnee0E=,iv:PO7sZbMVLZQBAijiDPVhOq/7dPe3omjyFtobyccfizU=,tag:l13uTLj9m/hImeseXYDbcg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL0hFUDc2RzEzeHhMdjVh
            N1dDaE9XVCtiN3BST29mMG94N2pFV21mRVU4CnZpeDY4TStQekRGMnVoN1hHZC9k
            Qm9lUTNPVDV3bW82NnRXMmdSY1dmWUUKLS0tIHN6ODRGa1R0Q0wrQWlUMzllZDND
            cWVlT0dmdDR4ajF5WnVjUnFlYTM1TG8KpziHmRszNsDzAfueJm/Jrk9qk2Oy+Q5G
            raPUl8uZCkGB9TwWtLv5s7AIk9eTadj3gVVI60shKOOiFar6L1/aoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T07:17:58Z"
    mac: ENC[AES256_GCM,data:8qoP8PT1TNQr/tWIwGt7v0A6SZenmWTO1dbICifvbuHAk07nP3a4KHiUmzISoWyPXodGP37gWj+dUTeT2zjdj/aJPjsj/N8LQTeemWSMSPSx/pHDiyndXYrwLp5CRhdiRxot/S7wHxMm7VwVf6hapfVa0BD9qJaxbFgIBOrK4sM=,iv:i0k2rRwlw9N0CsLbc+N0zzLKQPTORQppMKuu6RbMZFE=,tag:PSxqiwDm5AmCZEE2v2DZUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
