
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name:  open-webui-backup
spec:
  sourcePVC: open-webui-data
  trigger:
    schedule: "*/600 * * * *"
  restic:
    pruneIntervalDays: 1
    repository: restic-open-webui
    retain:
      hourly: 5
      daily: 4
      weekly: 3
      monthly: 2
      yearly: 1
    copyMethod: Snapshot
    storageClassName: longhorn-backup
    unlock: "something"