apiVersion: v1
kind: Secret
metadata:
    name: tns-csi-secret
stringData:
    url: ENC[AES256_GCM,data:noljGJJ93W0CnCWnyPQ38FQWsAqGjFd6kplhecxK/tA=,iv:8Is4aKN41H3HHFz4zmEBmq/6lsQUS/ZWy3Wmjnlj5yc=,tag:LpNmR6QIMA32YzHavq9G5Q==,type:str]
    api-key: ENC[AES256_GCM,data:VPjXlzG7lJcKgujg28xPvHm/UqJ4VxI5tVmFZjIkawXtpKFJ13GX+8G9obwJgrxoygj8vRQCcT6mJCCyVQtnBgX/,iv:aFK6KIHkqRZPKcGBRY2Ch0e7TvGV0FMq1MF5z32pTOk=,tag:1aaf997rxb+rd/zN0uskJw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T15:44:03Z"
    mac: ENC[AES256_GCM,data:LXVGePpHmPW3Yz7IL9K/vbJ0ewsjy2FkMz3RFhyPvvMRPP58UDBxHW0HCzstt2xwuaeukGwdMA7Zri7NvoSOcu4YpiVeYNPpZkR/2aic1INBu44dS90ATBUuOONd4MCRcPlDvWpEOiuPq4wQ5FtWG5oDCtiehdS0JVC3qf9/PsI=,iv:FQv17DbgZcPIJ7D0iEzvkWEMZADAA3dg0TY/gejygrs=,tag:hm+Stku1NtKAJr1BaRyXQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
