apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tns-csi-nvmeof-retain
provisioner: tns.csi.io
parameters:
  protocol: nvmeof
  pool: "nvmepool"
  parentDataset: "nvmepool/tns-csi/pod-volume"
  server: "10.0.0.154"
  transport: "tcp"
  port: "4420"
  csi.storage.k8s.io/fstype: ext4
  deleteStrategy: "retain"
  markAdoptable: "true"
  adoptExisting: "true"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
