apiVersion: apps/v1
kind: Deployment
metadata:
  name: dozzle
  labels:
    app: dozzle
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dozzle
  template:
    metadata:
      labels:
        app: dozzle
    spec:
      serviceAccountName: pod-viewer
      containers:
        - name: dozzle
          image: amir20/dozzle:v10
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DOZZLE_MODE
              value: "k8s"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dozzle-data
