---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dozzle
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: dozzle
spec:
  tls:
    - hosts:
        - dozzle.cloud.traunseenet.com
      secretName: dozzle-cert
  ingressClassName: traefik
  rules:
    - host: dozzle.cloud.traunseenet.com
      http:
        paths:
          - backend:
              service:
                name: dozzle-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
