apiVersion: v1
kind: Secret
metadata:
    name: restic-dozzle
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:aU1uIlaSGQ5pJ7EQBTU3bxHpofytfGnwSPUKQQBIutaEeD1LblSj92iAb40aNVAm7FXplaHo,iv:6DDznrd0rQA9ceXRQyxHXuwJDJiJsdowrjxAQhhre1A=,tag:X5jACiqQS29h0Fp1D+4BkQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:eayBHluQfs6NQQPQ2Kn8S4M/CF7KrGxC0SgYFuooq9KdIm8ct+axux2ypj7I,iv:0YwKkcguxB7wIOaMKtYipilXxcmJ3XKdt3x6rJnpHnQ=,tag:0jx7EoSsA2cmroE/CDNY/A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zQYchXDD06D1OLDaaJK60BIsr5o=,iv:WRFfRJqKcFPHcMR0LV9WS2AcvYS7k1y5NxGydZwK9eg=,tag:mkm/p1kt+QjyNr6xLR+JRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1ydCU/k5eFsJFpQBLldan1tKHZEaZtnVg6K+O86QHpGk7gFZ/I61nw==,iv:IkDuVMcynCXLLV4nnpuXXmeGKhnNy0iOfndldiTgtVw=,tag:67k18ABLGcxqTyxKDdjjHw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T21:32:11Z"
    mac: ENC[AES256_GCM,data:7UQ3iQAVDlUNd8GRo1W2ZjCL2D/Z5CQbljnY0O6zgqnRxSwfX9yajpU7LEwwwRc4XP9WEoR217S9g9z+jh+NaIbIZblY74fl25GOT80zb7mvxzVgIWGsCKAM37C2YirwZoa8GRKZuK1dfcD5aHDfu07fSq3xxIdQa48E8egMuHU=,iv:U9IoAdWiWRcpCTntXxagFMzjzMaO8f7ffqkPx0bRA4I=,tag:8sWX2KYccVW055EIPAkDRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
