# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release-dashboard.yaml
  - release-beyla.yaml
  - release-loki.yaml
  - release-tempo.yaml
  - secret.yaml