apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
stringData:
    client_secret: ENC[AES256_GCM,data:kcQR4tAeVVbgr05oKgdVjhf9dpayWsiq8J9+1g7wBT4=,iv:6J3j5DtwOF7DEbV/gObTcM3l5GUlS3sSmFypKeuWzgA=,tag:M6ePdqEf7yluEEthI7VZDQ==,type:str]
    admin_user: ENC[AES256_GCM,data:2bnY4ZP+zExAbwTQrg9juw==,iv:10y4dyG/5jEuDKa+1mecSrNn71AZWHO8G3VDAus+TPc=,tag:SA77PTgSQOTqYGrmr0Vfnw==,type:str]
    admin_password: ENC[AES256_GCM,data:9XGtdFdWh0+5LhKL2nKRRkHBTAsTVc4aERo=,iv:E5v2b+rSH+aOrEURb8oM1LTbLvYplQi9ZxcJCP1md6c=,tag:UFYyxSYkPHTEzhmlhmkasg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T12:17:58Z"
    mac: ENC[AES256_GCM,data:KnjqllPsLuE7dYZAGapLThzRybxT1eAqhUsbrS//MAH25e9DQNBSPVYa2Tw90fZla3aB3QDYgVIE3/rZkunGSNoQh23+roX/TtQyIebshmv+iq6EU4cDYjxCxL2U+/cftLagWZ4Nz8FTWJfKbziXUvRW2vIZMCjB8IOq+enmo8Q=,iv:8dJaLDRvh011WztHIfcRm6pDQCtHkQMLXvy8dniJjAM=,tag:hxtDrabtFuQ2fPMvXZacPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
