apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
stringData:
    client_secret: ENC[AES256_GCM,data:kcQR4tAeVVbgr05oKgdVjhf9dpayWsiq8J9+1g7wBT4=,iv:6J3j5DtwOF7DEbV/gObTcM3l5GUlS3sSmFypKeuWzgA=,tag:M6ePdqEf7yluEEthI7VZDQ==,type:str]
    admin_user: ENC[AES256_GCM,data:bVTAk1st/jytxOM75Z8S5A==,iv:oRgjlFA5zmv6uVxai4qpbyeAVkVkTDZAOSINX5DuEmg=,tag:e5UVj+oTjC6GZRf6uo99nA==,type:str]
    admin_password: ENC[AES256_GCM,data:9XGtdFdWh0+5LhKL2nKRRkHBTAsTVc4aERo=,iv:E5v2b+rSH+aOrEURb8oM1LTbLvYplQi9ZxcJCP1md6c=,tag:UFYyxSYkPHTEzhmlhmkasg==,type:str]
    admin_email: ENC[AES256_GCM,data:i04OescM7uFf8/hqeRrvhQ==,iv:6y4gATUwFfI0wHrhEln0GdiX69d9FYBuY/SynWv7vtc=,tag:mRzUpUzdFnpm64wWCKqoWg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T12:35:34Z"
    mac: ENC[AES256_GCM,data:q642ElwshyeTidTowZ+ljAbpfNSYxh1gk3On9eVhARrznUG4rfu7sKttKzkyLu8GmcKFzZyNh53idv2ofuECWALg3gV8l4ZD2W4ZWAzF5HhvcYCPL/BYobvvQYB6befAu+BSkyURT5Tr4XSraal33D5D1eaGb9tEHLkLEdqE8w0=,iv:hG+r0aN0Lj7jsJ+P+w6B6w3DyG1QNetm3pEHbhp4qRc=,tag:QbHro2wQd+ZiHpRmu6Z7GA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
