apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
stringData:
    client_secret: ENC[AES256_GCM,data:kcQR4tAeVVbgr05oKgdVjhf9dpayWsiq8J9+1g7wBT4=,iv:6J3j5DtwOF7DEbV/gObTcM3l5GUlS3sSmFypKeuWzgA=,tag:M6ePdqEf7yluEEthI7VZDQ==,type:str]
    admin_user: ENC[AES256_GCM,data:7+NUGPXQoZPQaQ==,iv:WsIwQqqjqKtXA3z3F8z6xiZaeQDYoY5pQJ/Y4YJaE5s=,tag:VafpT9/PrJ/WFsc2JE8VzA==,type:str]
    admin_password: ENC[AES256_GCM,data:9XGtdFdWh0+5LhKL2nKRRkHBTAsTVc4aERo=,iv:E5v2b+rSH+aOrEURb8oM1LTbLvYplQi9ZxcJCP1md6c=,tag:UFYyxSYkPHTEzhmlhmkasg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T08:44:22Z"
    mac: ENC[AES256_GCM,data:b4SPg2W+ikHRhAOKrqFGmxzzCjXmVdToxV0vcMUO5apdiLovKrLReRQoUBty6HLVLvT5tRVypAqxJlX5BTYmg+MhGYhLjgd60rLozbs/ojG8h+88YF4RgUU/FvOeP9N7AUOH9K7Z8SEKsugXZrvu839dPGxtjw6kmuHiUKKSm/E=,iv:psPYD0g1GNJ6UiULiwKWfJQUpzDXGIcsiJgWshVN26M=,tag:jgbVqwWpCXZMG2RwHf/53A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T08:44:22Z"
    mac: ENC[AES256_GCM,data:b4SPg2W+ikHRhAOKrqFGmxzzCjXmVdToxV0vcMUO5apdiLovKrLReRQoUBty6HLVLvT5tRVypAqxJlX5BTYmg+MhGYhLjgd60rLozbs/ojG8h+88YF4RgUU/FvOeP9N7AUOH9K7Z8SEKsugXZrvu839dPGxtjw6kmuHiUKKSm/E=,iv:psPYD0g1GNJ6UiULiwKWfJQUpzDXGIcsiJgWshVN26M=,tag:jgbVqwWpCXZMG2RwHf/53A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
