---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-base
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/longhorn-system/longhorn/base
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: longhorn-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-addons
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn-base
  path: ./kubernetes/apps/storage/longhorn-system/longhorn/addons
  prune: true
  # wait: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: longhorn-system
