---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: app-users
    netbird.io/policy: app-users
    netbird.io/resource-name: "navidrome"
spec:
  type: ClusterIP
  selector:
    app: navidrome
  ports:
    - port: 4533
      name: web
      targetPort: 4533