apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: https://ntfy.cloud.traunseenet.com
    behind-proxy: false
    proxy-forwarded-header: "X-Forwarded-For"
    cache-file: /etc/ntfy/cache/cache.db
    cache-duration: "12h"
    auth-file: /etc/ntfy/auth/auth.db
    # auth-users:
    #   - ${NTFY_USER}
    attachment-cache-dir: /etc/ntfy/cache/attachments
    template-dir: /etc/ntfy/templates
    upstream-base-url: "https://ntfy.sh"
    # upstream-access-token: # if ratelimits occur, set your ntfy.sh access token here
    log-level: info

