apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
data:
  NTFY_BASE_URL: "https://ntfy.cloud.traunseenet.com"
  NTFY_BEHIND_PROXY: "true"
  NTFY_PROXY_FORWARDED_HEADER: "X-Forwarded-For"
  NTFY_CACHE_FILE: "/etc/ntfy/cache/cache.db"
  NTFY_CACHE_DURATION: "12h"
  NTFY_AUTH_FILE: "/etc/ntfy/auth/auth.db"
  # NTFY_DEFAULT_ACCESS: deny-all
  NTFY_ATTACHMENT_CACHE_DIR: "/etc/ntfy/cache/attachments"
  NTFY_TEMPLATE_DIR: "/etc/ntfy/templates"
  NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
  NTFY_ENABLE_LOGIN: "true"
  NTFY_LOG_LEVEL: "info"

