apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secrets
stringData:
    NTFY_USER: ENC[AES256_GCM,data:IqtKF3lIlYU35lzE,iv:1fTrl/viBvdmLhDEKDhxiRP6q6lgY+dwAPw7LOeQJU0=,tag:s9XoMgO8jnjV0iGopJuHBA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T07:40:12Z"
    mac: ENC[AES256_GCM,data:Fwj5SYMjBSVML2L3e1Dxnb8QFQGGzMuxhHYS5BCZ9CnJmrMtqKsCuAqHqlD9oMgxwQKZOiRL4TrDRoWPZAxZXq7IT8faLwWpiBeVVFAu0oobISQYxeQSGr5jrJsnxfr3+l4prkG8t3rYgmZuNnR8Bczehqoi2XwQVLzu6qtY2Yc=,iv:jR660/9mDqktEcI6THQwpJXUty/D9frPWoBcTSOBCHk=,tag:clGZGaYVYayphWJz14ii3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
