apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secrets
stringData:
    NTFY_UPSTREAM_ACCESS_TOKEN: ENC[AES256_GCM,data:oFiTZNddZGUtgFY/KWE2yOOkQ4fMu+Q3rOAhXxIuagM=,iv:B34OO9qKj+7XRq+E1n6VscnyIPINhJcQa3cP+HduWVw=,tag:HFpinzUKVcgmx0sTliPqeg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T08:54:20Z"
    mac: ENC[AES256_GCM,data:A9Nj2e6u1uOCGI22A9lrRNji/cRQmz2etcWpTMG6vMzMnTx5haQIVpacyWEOZ2xGw+TguuVUyw+rfkaPloUGYCBKhx5Iaf7NYwq/xsHcVF+BqHZly27wjryjFfOyVb2+dcM4L8JfBQp0mt7eGXazec0duv8SnSU7V4d1NxNRW34=,iv:wAt2/legAu5OVcRqwWG5U6iDXi0WnpkJtlugcPoXWXA=,tag:z0VeI2Wo41m8CL334r4ZLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
