---
# Basic service for port 80
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  # annotations:
  #   netbird.io/expose: "true"
  #   netbird.io/groups: app-users
  #   netbird.io/policy: app-users
  #   netbird.io/resource-name: "ntfy"
spec:
  selector:
    app: ntfy
  ports:
  - port: 80
    targetPort: 80
    name: web