---
# Basic service for port 80
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  annotations:
    netbird.io/expose: true
spec:
  selector:
    app: ntfy
  ports:
  - port: 80
    targetPort: 80
    name: web