---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: uptimekuma
  name: uptimekuma-data
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-storage
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: uptimekuma-restore  # Name of the ReplicationDestination
  resources:
    requests:
      storage: 1Gi
status: {}
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: uptimekuma-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-uptimekuma
    storageClassName: longhorn-storage
    accessModes: ["ReadWriteOnce"]
    copyMethod: Snapshot
    capacity: 1Gi
    enableFileDeletion: false
    cleanupCachePVC: false
    cleanupTempPVC: false

