apiVersion: v1
kind: Secret
metadata:
    name: restic-uptimekuma
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:hgm5SavxBedyvBR+I9Bgj/qBdvw41O7MSgCau/uhaeRJf+g3g9nGbUIEs53rKzz12OCVQzjUUwdBuw==,iv:LJfAZZ4LSwMn9hCytH+ZDXN9zGXL117ITE0zQbaR0oU=,tag:/YbWRbJcsvvQXwp5ZMCqzQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:uJsnpQjEm7YMKufL6/EUtaIav9O0P2AB96z6lK5lq3P4gT6qcZ2tuw==,iv:O++V4BQgkQpCLECo0SKYHGQH6I/XNTRaHw6ax1VYmQI=,tag:fHfc+nmIyRHLpT+eVBB/+A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6fMZOZyN67r1Ml+af8xe2uEmWMQ=,iv:vAp5DYPQK7JW62NSMgruw9ek6y1kSyPIoCCkNfQIvVM=,tag:zO+H14lQQy51E9lUl0F1ZA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Fnsq6TnSEk9/zR+vrCE5qUribf2IVGjzv4wUk4xkOjhr6/5ZxZeK8w==,iv:cD4i2UgKWEdi0ijM0qbiuUOybmTMpsH82ggngEOjk+o=,tag:eIg4m8WZRcLquYLAqJygLw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmZPQXduK0daRVhidnJ3
            VUNBaTE0dGtpVE1kM0wxamFBQ0wreStUVEJJCk8wWkNMc2hvTmhSMkM5bmN6dFR4
            Ny91R0hFcUVYa01ENFhBUmRVRnFOUG8KLS0tIDVvR3B4aTZGNExkUmh2VGlkOTky
            NHlDRVVJUkVVWi9QNnZ6d1FwdDJvNGMKktKIIWrqfKdhoBRW4oXvQIGBwSZ5f9ue
            YNRd5uuhhz2RIk1DGJMTbN00IrTp8dZquSn8dT25g2tiNxF4LU/inA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T14:22:55Z"
    mac: ENC[AES256_GCM,data:SZ/ECZIwlnC8LhBt2AGro/GQz/wnlqlutoZIbQ+OhMV37ajAsKPoF4hVH9o/Tfc/xAvH/hVcNTsgBTHjcj4lhz1hlo3RbUkoKZ6+7wNGe3rD2vyluutdf1z8wtFiMtUEjBRlH0Mlp/fsmANUBNAdfVSis6tHTxtP84vp0VBYVBw=,iv:nEiPBNIFlJnI5ESlPRCbDRfOEoEAWAH+jtQ1XkG/vOI=,tag:LaitTZ5oHRSAHR0atP66qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
