---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: openwebui
  name: openwebui-data
  annotations:
    numberOfReplicas: '1'
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: tns-csi-nvmeof
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: openwebui-restore
  resources:
    requests:
      storage: 5Gi
---
#yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: openwebui-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-openwebui
    storageClassName: tns-csi-nvmeof
    accessModes: ["ReadWriteOnce"]
    copyMethod: Snapshot
    volumeSnapshotClassName: tns-csi-nvmeof-snapshot-detached
    capacity: 5Gi
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
