apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:103gRhNIhF4s59Xi7eHqxl2qHvARW1FngSVhHiP23fbEl7qq,iv:mblltnzMaMB/X2xp73hca1Bo69HW9E0icb4/9uyCxPc=,tag:QkUKnKeUaLAlsG6MsuA6zg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:hTRDKxxHxEROQzaH3mGtpNsiLElzkTTkV2h5jGtMiS4=,iv:2jPCG7li1vwVlplQpCv6uHNHiWSdFGQf6DQ7ib57J5k=,tag:VfTU8fRucpqkQXt5ivjiNQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Drpx6tOvWHLlZ7jaRNOPW5aINW0=,iv:XP/ETBnS0Hccq98RjrVQtSfVmG+kdIdLUbJvyAw95P4=,tag:CLxHxObr0KUF1c0cuQO2PA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T08:17:12Z"
    mac: ENC[AES256_GCM,data:mTZ2yye+uNGkzCkIAToedQ9zl3AjUHx9aAxeppkiOy0S5G0WiSkpW4SXjVQ5lHv2gujGBFNGENC0QCrg2rhavtTQbgYDIUEmDYz/91Hhg7NuLf5BntbSPg8PlV5iRLoVHpGfNEQXPAypGy2IgkA9PB2c/aWfaIAS0gpt97AVDM0=,iv:rmTyZd4UWADb4KzM5yG/H6/9f6mwi6xeb3iSVmJEcik=,tag:Uqe6eTMjfcmm+R7Tmyyggw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
