apiVersion: v1
kind: Secret
metadata:
    name: open-webui-oauth
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:9Xskw8eLCYKiiSJ4XvWgGgMBhDz4InymXiRj5B2nqK6I4QFg,iv:LP0BNoixDcIhW/pBeD/Jl3i3cFFF3pLnUrpvqdJv6P8=,tag:VW0tdcyigi00atN0Q/jJyg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:YpOT8ccGQOnkmhQQM2kNzlwrNXp0IcQM2GApbvM6T9E=,iv:AhjI0V08Hx94wm3fbFU0xZtwxTDeLQq3U9+5mFf6uZQ=,tag:zgPVEn9zIjMRPryXQvBAFA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T07:17:12Z"
    mac: ENC[AES256_GCM,data:T4Wfp2pQZ2Af48FeieYLAxD/0rcsiWYDy9Aug4bdOJhMV/j/ugMJtyvs1n9lnbb3tWLxv0nGA7O6MQQ00KuHFNm2uoUbYzVgMtAJo9AubjNn+/nuFLnn6L/zAMQjaf082rY2r6BxMhZik94Mna2kcPSofix9L165FsWa4B2mJa8=,iv:WxKPiSDG30NrsPCMZ/UrLN1jHtvG87zBzaUGP1PX1io=,tag:N9P0Wp3L12RTt3RRvf8j+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-open-webui
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bVgCw0ruuMqH6Q4u4MiZjz36TWi29nWVjGJdtqPsHpQU8+XxFHzp49Pg6cmLPV/QstA6/rwa1k86vw==,iv:p16CFl2XpWPkaguM77n+xs7dZQKbbvBeC8CHbXsd9eE=,tag:zIj+HWFtxK/+0jvt/X3/cw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:bbGGIqR62cqNbgONWuf0ovv0EBPK+OENnZdtGCtj8GOqaAynVQ==,iv:ihHfXL2XVdtqb5QLUyirwmEcUhrlNcRetdHFlJv8Jlo=,tag:/gbokbWk+mhHMkQh8iMGog==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:B4eos2YIR5gTqn8jH0E1+9tbm0c=,iv:QiTaeRSqJhXi+OV9eivF2g/AEQoOlcZ+3VzvYoToMrU=,tag:+EdZGtNnqRlcFDiixgAAEQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ciZ1QXiPiHOGkeN5P3VOpTIl/Psg6WmvbBdWCil7MuhefPgr0cJdaA==,iv:mFbWjKwpK9XHMaAX7hCAbx7bMcEtFC4cWLowrsZ6nWU=,tag:1WeSXWQNWE34VUSlTK310A==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T07:17:12Z"
    mac: ENC[AES256_GCM,data:T4Wfp2pQZ2Af48FeieYLAxD/0rcsiWYDy9Aug4bdOJhMV/j/ugMJtyvs1n9lnbb3tWLxv0nGA7O6MQQ00KuHFNm2uoUbYzVgMtAJo9AubjNn+/nuFLnn6L/zAMQjaf082rY2r6BxMhZik94Mna2kcPSofix9L165FsWa4B2mJa8=,iv:WxKPiSDG30NrsPCMZ/UrLN1jHtvG87zBzaUGP1PX1io=,tag:N9P0Wp3L12RTt3RRvf8j+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
