apiVersion: v1
kind: Secret
metadata:
    name: open-webui-oauth
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:9Xskw8eLCYKiiSJ4XvWgGgMBhDz4InymXiRj5B2nqK6I4QFg,iv:LP0BNoixDcIhW/pBeD/Jl3i3cFFF3pLnUrpvqdJv6P8=,tag:VW0tdcyigi00atN0Q/jJyg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:YpOT8ccGQOnkmhQQM2kNzlwrNXp0IcQM2GApbvM6T9E=,iv:AhjI0V08Hx94wm3fbFU0xZtwxTDeLQq3U9+5mFf6uZQ=,tag:zgPVEn9zIjMRPryXQvBAFA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T11:20:38Z"
    mac: ENC[AES256_GCM,data:/NL8fK7kg3o1AZ+uuH2wxVC+rcy2zd6ra9Kt95IZqr9tAMNX74yrUAExwFDrswPVdDcqYKfJ6zl2B+RVhoyFwfYE9X14uKAZXzQU3qkreuHZjJY8oonZl+/B8q5OSsyVhagRhnbGaeXhvghIivof+WZyLV0lPKIQVJ0IFd/QE4c=,iv:bblmCptHbOnuAufLO1DSnKSoSe2IpaV1Syn5BZaagFw=,tag:SWcPrafjk9hEw6RVIIyweQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
