apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:103gRhNIhF4s59Xi7eHqxl2qHvARW1FngSVhHiP23fbEl7qq,iv:mblltnzMaMB/X2xp73hca1Bo69HW9E0icb4/9uyCxPc=,tag:QkUKnKeUaLAlsG6MsuA6zg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:hTRDKxxHxEROQzaH3mGtpNsiLElzkTTkV2h5jGtMiS4=,iv:2jPCG7li1vwVlplQpCv6uHNHiWSdFGQf6DQ7ib57J5k=,tag:VfTU8fRucpqkQXt5ivjiNQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:1+ftRGq2CybRG65bZmmTMAY=,iv:dwleC2ZQfU16g967cwYCIwA5/OYd7mXyUClxvAFvlv4=,tag:5QqYFFrl3FkhskwMvMiuTw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T21:02:06Z"
    mac: ENC[AES256_GCM,data:1lp5bRbI6k1lO4L8Q/st91d4SszeaiZ0J6esNgmWurr6aWOmnSeyE9/rk5NIwT806xARIZKcyavvhQ8RTT5R6qi0PMHGYxFDpYMHN7MOk6oZOafSOz5VuqzxO7GBYgi0J9vbESqgFK49NwGI4RvBtGu3vMxF7W5+kvaZ1NF1bCo=,iv:Rk3fI2w/oTe9tMBdOZS+dICtxPGIAIvldVwIKK8OOuQ=,tag:57pfFG0td3hCUhFXejSuWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-openwebui
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:l0+krYpivpZPkCA9Sf49aY3GI/v94IleEGmk/F1W9XXtTvUENj6dN4A+ykn4LE0O5YF2eEpyeOgs,iv:cAhsaAkrTsP1hL4dRijkjO9KeSMga5x0dtqAIWUoX68=,tag:SZZgGSjjmC1EW9GapGbpUA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Hv0Yw3uJMAZ/nMVjQsUGUWE9Tuoje7BoHYhu2RiBjVduQPSbh4shfEoR5ERh0W1/cgk=,iv:k9mOUp3uHaITF18+apnQoPZ5CmVpRE14odDOnlZrxYE=,tag:6V18k3EdWfwhKR8AJLMVWw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TfB2EQEpmYL18ZBhfWVCurJXmtE=,iv:FRG3V0aGMXuQW7hjl7XSmOtivNqylNN+J4cMH/GxbAg=,tag:X9MF51Fmt99YNMl7MtEo+A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:upcFdRMi7+hXFD6Pbs6BKupkrdS02DVmY6atJ/GC9c2uLLtw8Ze/NA==,iv:Dj8NywB28qklDHJVou/0YhW/gtWVwwG/bsnHh3Bwd4k=,tag:omeTl2RiTGEpNrKlsZL7JA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T21:02:06Z"
    mac: ENC[AES256_GCM,data:1lp5bRbI6k1lO4L8Q/st91d4SszeaiZ0J6esNgmWurr6aWOmnSeyE9/rk5NIwT806xARIZKcyavvhQ8RTT5R6qi0PMHGYxFDpYMHN7MOk6oZOafSOz5VuqzxO7GBYgi0J9vbESqgFK49NwGI4RvBtGu3vMxF7W5+kvaZ1NF1bCo=,iv:Rk3fI2w/oTe9tMBdOZS+dICtxPGIAIvldVwIKK8OOuQ=,tag:57pfFG0td3hCUhFXejSuWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
