apiVersion: v1
kind: Secret
metadata:
    name: pangolin-proxy-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:o26/xEZruLU8jKhN0W/jMKOu8VQvH1MPHQn20b4z5no=,iv:pX+TOoYHEiRwSXvWeFG53FEWaqRNAwHj6KA9PAe5rhA=,tag:M6T4CFEAKKGJqtJi64qqNw==,type:str]
    OLM_ID: ENC[AES256_GCM,data:DvqvlOca3yqaReG0f9mS,iv:0meQWmhMyS2TkQhiV2Y+WuAVprMRxLk9AuyeafVDn3A=,tag:mqWr3HptwiqOMy26mMh2tQ==,type:str]
    OLM_SECRET: ENC[AES256_GCM,data:KiXykEJ1J6Y8k/LbB/WtO85+ToBpu2Vzjc88fqeEkg1NkNbgDj2EIVDTFJZ7DAyz,iv:MeUQ6/z498B/YcDQnVtXt0Yl1Amx2Jdm2ZCDFAtM/iE=,tag:y0K2UBXh4Meacnh8Da8vTg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T12:45:46Z"
    mac: ENC[AES256_GCM,data:4cJ6+v421ng0YyyOXUce+WY+hySOLkKZ+zYdVD3EJca9mFTpntlvf2bF0CAM03ct/gwu5n2G4uwbaTeK/IaNrGCAbawodcY23XfDmiLMz6n8Ix+Whx5KSrOoCBqGR16YDomLFqQPLBrL0rf484b+YBmzFPDD+hGhvUu6Xw//cwE=,iv:T9boazoOLuCgXq4Kvwu8cDtgTyKgkBvlWIuwvwgCNDg=,tag:/6ttUk45G3JC8OyHWRmwqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
