apiVersion: v1
kind: Service
metadata:
  name: pangolin-proxy
spec:
  selector:
    app: pangolin-proxy
  ports:
    - port: 6060
      targetPort: csm-metrics
      protocol: TCP
      name: csm-metrics
